### ISSUE TITLE
[Suggestion] Empty line after csharpfixformat.style.braces.onSameLine

### ISSUE THREAD

**Issue by Kris-** [Leopotam/vscode-csharpfixformat#10]
Add an option for an empty line after the K&R opening bracket.

Example:
```
void Function() {

    // ..code with empty line above...
}
```

**Comment by Kris-** [comment]
I only want this for classes and function openings, not if statements and such.

Great extension otherwise. 10/10

**Comment by Leopotam** [comment]
@Kris- you can use csharpfixformat.style.braces.allowInlines=false for this behaviour.

**Comment by Leopotam** [comment]
> for classes and function openings, not if statements and such.
Its not possible in current implementation due to its not real c# parser, but most regexp textual fixer. There are no context differences between body of function or body of conditional / loop expressions.
