### ISSUE TITLE
Is it possible to only use the "Organize Imports" feature?

### ISSUE THREAD

**Issue by fabiob** [Leopotam/vscode-csharpfixformat#100]
Hi. I'm a big fan of your extension. Unfortunately we're using some of the C# newest features, and sometimes the formatter does more harm than good. So I've recently switched back to the OminSharp formatter.

However, I really miss the way your extension sorts and organizes the `using`s. So my question is: is it possible to extract just that part of your extension, so we can have a "Organize Imports" command?

**Comment by Leopotam** [comment]
@fabiob `csharpfixformat.style.enabled` = false

But better to request this feature from microsoft dev team of omnisharp.

**Comment by fabiob** [comment]
> You can do it by yourself, fork repo on github, remove useless parts and build new extension locally.

I'll give this a shot, thank you :)
