### ISSUE TITLE
enum in variable name causes incorrect formatting

### ISSUE THREAD

**Issue by LeedsCode** [Leopotam/vscode-csharpfixformat#102]
### C# FixFormat extension version:
0.0.82

### VsCode version:
1.36.1

## Steps to reproduce
Paste the following code in a new file. After saving, format the file.

	using System.Linq;
	using System.Reflection;

	public static class EnumExtensions {
		public static string GetDescription<T>(this T enumValue) {
			var genericEnumType = typeof(T);
			MemberInfo[] memberInfo = genericEnumType.GetMember(enumValue.ToString());
			if ((memberInfo != null && memberInfo.Length > 0)) {
				object[] attributes = memberInfo[0].GetCustomAttributes(typeof(System.ComponentModel.DescriptionAttribute), false);
				if ((attributes != null && attributes.Count() > 0)) {
					return ((System.ComponentModel.DescriptionAttribute)attributes.ElementAt(0)).Description;
				}
			}
			return enumValue.ToString();
		}
	}

## Expected  behavior
Formatting is correct, no changes.

## Actual behavior
The lines following if statements are no longer indented

	using System.Linq;
	using System.Reflection;

	public static class EnumExtensions {
		public static string GetDescription<T>(this T enumValue) {
			var genericEnumType = typeof(T);
			MemberInfo[] memberInfo = genericEnumType.GetMember(enumValue.ToString());
			if ((memberInfo != null && memberInfo.Length > 0)) {
			object[] attributes = memberInfo[0].GetCustomAttributes(typeof(System.ComponentModel.DescriptionAttribute), false);
			if ((attributes != null && attributes.Count() > 0)) {
			return ((System.ComponentModel.DescriptionAttribute)attributes.ElementAt(0)).Description;
				}
			}
			return enumValue.ToString();
		}
	}

**Comment by Leopotam** [comment]
@LeedsCode can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@LeedsCode no feedback, closed as fixed. 0.0.83 version released on marketplace.
