### ISSUE TITLE
How do I configure it to apply formatting as I type without needing to call the format command

### ISSUE THREAD

**Issue by cosmo-naut** [Leopotam/vscode-csharpfixformat#103]
### C# FixFormat extension version:
0.0.83

### VsCode version:
1.37.0

## Steps to reproduce
Type `void test() {}`
I press enter and it turns to 
```
void test() {

}
```

## Expected  behavior
Why is it so hard that I can't find a way to put the curly brace on the next line by default.
I know this is not your fault I just wonder if your extension is capable of this
I have been searching for how to do this for a year at this point and no luck
```
void test()
{

}
```

## Actual behavior
I need to call format command `ctrl+k+f` for me

**Comment by Leopotam** [comment]
@cosmo-naut did you read [README](https://github.com/Leopotam/vscode-csharpfixformat/blob/master/README.md)? There are 2 options:
> `csharpfixformat.style.braces.onSameLine`: Should open braces be kept on expression line (K&R style) or on new line. True by default.

> `csharpfixformat.style.spaces.beforeParenthesis`: Space before '(' - opening parenthesis. True by default.

Set both settings to `false` to get what you want.

**Comment by Leopotam** [comment]
@cosmo-naut is issue fixed for you?

**Comment by Leopotam** [comment]
Closed as fixed.
