### ISSUE TITLE
Newline had bad work with backslash and ignore comments

### ISSUE THREAD

**Issue by AtsushiYamashita** [Leopotam/vscode-csharpfixformat#104]
### C# FixFormat extension version:

v0.0.83

### VsCode version:

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

## Steps to reproduce

Try fix this code by this.
```
/* fixformat ignore:start */
var file_path_slash = @"\" ;
/* fixformat ignore:end */
```

## Expected  behavior

I think, will have been ignore at the line from this tool.

## Actual behavior

This code have been inserted newline after backslash.

```
/* fixformat ignore:start */
var file_path_slash = @"\
" ; // <- this newline is not wanted.
/* fixformat ignore:end */
```

I think, RegExp will bad works in current order.
Try other order of cheking ignore phrase.

I will want to make code with this.
Thanks for good tool. :)

**Comment by Leopotam** [comment]
@AtsushiYamashita cant reproduce bug. I created empty file, added example and all works as must. looks like you found some side effect of surrounding code.

**Comment by Leopotam** [comment]
Will be reopened on new info.
