### ISSUE TITLE
Strange formatting for verbatim string ends with slash

### ISSUE THREAD

**Issue by avin-shum** [Leopotam/vscode-csharpfixformat#105]
### C# FixFormat extension version:
0.0.81

### VsCode version:
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

## Steps to reproduce
Format the following class
```csharp
  class Program
  {
    static void Main(string[] args)
    {
      string path1 = @"C:\abc\";
      string path2 = @"C:\def\";
      string path3 = @"C:\ghi\";
    }
  }
```

## Expected  behavior
Nothing changed.

## Actual behavior
```csharp
  class Program
  {
    static void Main(string[] args)
      {
        string path1 = @"C:\abc\";
      string path2 = @"
        C: \def\ ";
      string path3 = @"
        C: \ghi\ ";
    }
  }
```

**Comment by Leopotam** [comment]
@avin-shum can you check last state of develop branch? is issue fixed for you?

**Comment by avin-shum** [comment]
It fixed the example, but if I format,

```cs
  class Program
  {
    static void Main(string[] args)
    {
      string path0 = "\"";
      string path1 = @"C:\abc\";
      string path2 = @"C:\def\";
      string path3 = @"C:\ghi\";
    }
  }
```

It becomes,
```cs
  class Program
  {
    static void Main(string[] args)
      {
        string path0 = "\"";
        string path1 = @"C:\abc\";
      string path2 = @"
        C: \def\ ";
      string path3 = @"
        C: \ghi\ ";
    }
  }
```

**Comment by Leopotam** [comment]
@avin-shum my bad, can you check again?

**Comment by avin-shum** [comment]
@Leopotam It looks good. Thanks.

**Comment by Leopotam** [comment]
@avin-shum 0.0.84 released on official marketplace, you can uninstall custom package and install public release. thanks.
