### ISSUE TITLE
Incorrect formatting for const int declarations on same line

### ISSUE THREAD

**Issue by AndrewYinLi** [Leopotam/vscode-csharpfixformat#106]
### C# FixFormat extension version:
`0.0.84`

### VsCode version:
`1.40.1`

## Steps to reproduce
Declare and then format the following:
```
const int a = 0, b = 1, c = 2;
int d = 0, e = 1, f = 2;
```

## Expected  behavior
```
const int a = 0, b = 1, c = 2;
int d = 0, e = 1, f = 2;
```

## Actual behavior
```
const int a = 0,
    b = 1,
    c = 2;
int d = 0, e = 1, f = 2;
```

**Comment by Leopotam** [comment]
@AndrewYinLi sorry, but i have no time to support this extension anymore. Better to write ticket to [omnisharp-team](https://github.com/OmniSharp/omnisharp-vscode/issues) for support proper formatting with custom styles out the box.
