### ISSUE TITLE
Extra spaces when using anonymous types with generics

### ISSUE THREAD

**Issue by AskoldMakaruk** [Leopotam/vscode-csharpfixformat#107]
### C# FixFormat extension version:
0.0.84

### VsCode version:
1.40.2

## Steps to reproduce
`public class Test
{
    public List < (int, int) > Array;
}`

## Expected  behavior

`public class Test
    {
        public List <(int, int)> Array;
    }`
## Actual behavior
Spaces after `<` and before `>` aren't removed.

**Comment by Leopotam** [comment]
@AskoldMakaruk sorry, but i have no time to support this extension anymore. Better to write ticket to [omnisharp-team](https://github.com/OmniSharp/omnisharp-vscode/issues) for support proper formatting with custom styles out the box.
