### ISSUE TITLE
[Issue] Verbatim interpolated string literal breaks after fixing format

### ISSUE THREAD

**Issue by Kris-** [Leopotam/vscode-csharpfixformat#11]
### C# FixFormat extension version:
0.0.21

### VsCode version:
1.11.2

## Steps to reproduce
1) Write a string
```
$@"
My variable: ""{variable}""
"
```

2) Fix format

## Expected  behavior
```
$@"
My variable: ""{variable}""
"
```

## Actual behavior
```
$ @"
My variable: ""{variable}""
"
```
Note the space between $@.

Error CS1056: Unexpected character `$'

**Comment by Leopotam** [comment]
@Kris- can you develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@Kris- no feedback, so, 0.0.22 released on official marketplace, you can check it, thanks.
