### ISSUE TITLE
Problems with formatting of c#7 out variables in Dictionary.TryGetValue

### ISSUE THREAD

**Issue by bruce31** [Leopotam/vscode-csharpfixformat#12]
### C# FixFormat extension version:
0.0.21

### VsCode version:
1.11.2

C# for Visual Studio Code (powered by OmniSharp) 1.9.0

## Steps to reproduce
Set K&R bracket formatting (not sure if relevant to issue)
use c#7 out var name  syntax in a dictionary TryGetValue expression and then format document

## Expected  behavior
            if (!dict.TryGetValue (key, out var value)) {
                value = new Object1();
                dict.Add (key, value);
            }

## Actual behavior
            if (!dict.TryGetValue (key, out
                    var value)) {
                value = new Object1();
                dict.Add (key, value);
            }

**Comment by bruce31** [comment]
still an issue in 0.0.22

**Comment by Leopotam** [comment]
@bruce31 can you check develop branch? is issue fixed for you?

**Comment by bruce31** [comment]
Yes that seems to have fixed it.
Thanks for quick response.

**Comment by Leopotam** [comment]
@bruce31 0.0.23 released on official marketplace, you can uninstall custom package and install public release.
thanks for feedback. 👍
