### ISSUE TITLE
Interpolated strings containing double quotes

### ISSUE THREAD

**Issue by fergalmoran** [Leopotam/vscode-csharpfixformat#13]
### C# FixFormat extension version:
0.0.24

### VsCode version:
1.13.0-insider

## Steps to reproduce
Auto format file with interpolated strings containing double quotes

## Expected  behavior
Interpolated string to remain unchanged

## Actual behavior
This
![image](https://cloud.githubusercontent.com/assets/309139/26072418/54c45652-39a3-11e7-95dc-1887ef5ff129.png)

Becomes this
![image](https://cloud.githubusercontent.com/assets/309139/26072441/6ac7b46c-39a3-11e7-84a7-83ca46c11aba.png)

**Comment by Leopotam** [comment]
@fergalmoran can you check develop branch? is issue fixed for you?

**Comment by fergalmoran** [comment]
Sorry @Leopotam but how do I install an extension from github?

**Comment by fergalmoran** [comment]
Works perfectly, thanks @Leopotam !!

**Comment by Leopotam** [comment]
@fergalmoran 0.0.25 released in marketplace, you can remove custom build from develop branch.
