### ISSUE TITLE
Multi-line parameters extra-tabbed

### ISSUE THREAD

**Issue by fergalmoran** [Leopotam/vscode-csharpfixformat#14]
### C# FixFormat extension version:
0.0.26

### VsCode version:
1.14.0-insider

## Steps to reproduce
Format this code block
```            
var StartInfo = new ProcessStartInfo {
    FileName = "pinfo",
    Arguments = $"argie bargie",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    CreateNoWindow = true
};
```

## Expected  behavior
Code to stay as it is

## Actual behavior
Second and subsequent arguments are extra-tabbed
```
var StartInfo = new ProcessStartInfo {
    FileName = "pinfo",
        Arguments = $"argie bargie",
        UseShellExecute = false,
        RedirectStandardOutput = true,
        CreateNoWindow = true
};
```
This happens for parameters as properties.

**Comment by Leopotam** [comment]
Bad news, but i have no time to work on this plugin anymore (i switched to rider personally). Right now i can only suggest you to split this expression to 2 parts: instance creation and fields initialization below. Another solution - set valid indents for all fields and wrap whole expression with "fixformat ignore" helper (you can find example at README). Cant say when i can fix this issue, sorry. :(

**Comment by fergalmoran** [comment]
Thanks for the update @Leopotam - hopefully VS code will allow this without a plugin soon!!

As a matter of interest, why did you switch to Rider? I try it again every time there's an update but I find it really buggy. I can't even build File-New Console App in the latest EAP?

**Comment by Leopotam** [comment]
@fergalmoran can you check code from develop branch?
About rider - it much faster now than was few months ago and it supports overrides popup without issues. About "console app" - i dont know, i use vscode / rider on osx only as unity engine development ide.

**Comment by Leopotam** [comment]
@fergalmoran - no feedback, looks like issue fixed. v0.0.27 released.

**Comment by fergalmoran** [comment]
Sorry @Leopotam , only seeing your response now.
FWIW: it's not actually fixed, just different.

```
            var StartInfo = new ProcessStartInfo {
                FileName = "pinfo",
                Arguments = $"argie bargie",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            };
```
formats as 
```
            var StartInfo = new ProcessStartInfo {
            FileName = "pinfo",
            Arguments = $"argie bargie",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            CreateNoWindow = true
            };
```

**Comment by Leopotam** [comment]
@fergalmoran cant reproduce it, on my test all lines were formatted correctly:
```
class Test {
    void Test1 () {
        var StartInfo = new ProcessStartInfo {
            FileName = "pinfo",
            Arguments = $"argie bargie",
            UseShellExecute = false,
            RedirectStandardOutput = true,
            CreateNoWindow = true
        };
    }
}
```
vscode 1.12.2 (public release), default plugin config.
