### ISSUE TITLE
OmniSharp stop works when I try Format file on a large project.

### ISSUE THREAD

**Issue by bernardbr** [Leopotam/vscode-csharpfixformat#15]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## Steps to reproduce

I have a large project with more than 2k *.cs files, and sometimes when I press CTRL + ALT + I to format a file, the OmniSharp stop works, the shortcuts stops works too and when I close the VsCode the process still running with OmniSharp (Image above). I've tried to catch the error from Extension logs but it doesn't appear.

![image](https://user-images.githubusercontent.com/4705034/28329775-6edc1458-6bc1-11e7-8137-b42fdd4987fb.png)

## Expected  behavior

The file format must work fine and OmniSharp didn't stop.

## Actual behavior

All functionalities of OmniSharp and VsCode stops.

**Comment by Leopotam** [comment]
@bernardbr can you provide example code that slowdown / freeze vscode?

**Comment by Leopotam** [comment]
@bernardbr 0.0.30 released on official marketplace, can you check new version on your files?

**Comment by bernardbr** [comment]
Hello @Leopotam I tested with the new version here and it looks like it came back working properly. Thank you very much!
