### ISSUE TITLE
Strange mangling of commented code that uses string interpolation

### ISSUE THREAD

**Issue by bruce31** [Leopotam/vscode-csharpfixformat#16]
## Steps to reproduce
Take a commented piece of code that uses string interpolation
```
//  .Select (d => $"{d} units");
```
and format it.
__vscode_pp_lerp_ strings are introduced.
I can only reproduce for commented code but I think I have occasionally had it in active code.

## Expected  behavior
```
//  .Select (d => $"{d} units");
```
## Actual behavior
```
//  .Select (d => $"__vscode_pp_lerp_start__"+d+"__vscode_pp_lerp_end__ units");
```

**Comment by Leopotam** [comment]
@bruce31 can you check develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@bruce31 no feedback, closed as fixed. 0.0.31 release on marketplace.

**Comment by bruce31** [comment]
Tested 0.0.31 with no issues on vscode 1.15.0
Thank you
