### ISSUE TITLE
No-Parenthesis ForEach loops: second line not indented

### ISSUE THREAD

**Issue by scriptorum** [Leopotam/vscode-csharpfixformat#18]
### C# FixFormat extension version:
0.0.31

### VsCode version:
1.15.1

## Steps to reproduce
Run "Fix" on a `foreach` loop without parentheses and a statement on the second line. The second line is de-indented to line up with the foreach.

![fixformat](https://user-images.githubusercontent.com/3144427/29745765-21e0aa16-8a92-11e7-911d-6882f26b3bd7.gif)

This formats correctly if it's a regular `for` loop.

## Expected  behavior

```csharp
            foreach(GameObjectPool p in pools) 
                p.Clear();
```

## Actual behavior

```csharp
            foreach(GameObjectPool p in pools) p.Clear();
```

**Comment by Leopotam** [comment]
@scriptorum can you check develop branch? is issue fixed for you?

**Comment by scriptorum** [comment]
Yes, it's fixed. Thanks!

**Comment by Leopotam** [comment]
@scriptorum 0.0.32 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by scriptorum** [comment]
You know I said parenthesis but of course I meant braces. Dur.

**Comment by Leopotam** [comment]
@scriptorum yep, just copy&pasted your sentence, my bad. :D
