### ISSUE TITLE
Feature Request: Format On Save

### ISSUE THREAD

**Issue by bsell93** [Leopotam/vscode-csharpfixformat#19]
Is it possible to hook into the format on save functionality that is built into VSCode. I believe Beautify extension is doing this now https://github.com/HookyQR/VSCodeBeautify/issues/59.

**Comment by Leopotam** [comment]
@bsell93 now its not possible due it not supported on omnisharp extension side in actual public build, you can check messages / links at another issue: #17

**Comment by Leopotam** [comment]
@bsell93 implemented in 0.0.39 version as default FormatProvider (with default formatting, format on paste, format on save, etc). You can test it with code from develop branch of this repo and omnisharp plugin from their [master branch](https://github.com/OmniSharp/omnisharp-vscode/tree/master) (0.13 version still not released).

**Comment by Leopotam** [comment]
@bsell93 0.0.39 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by bsell93** [comment]
@Leopotam sweet! Thanks!
