### ISSUE TITLE
malfunction about `#region `

### ISSUE THREAD

**Issue by netpyoung** [Leopotam/vscode-csharpfixformat#2]
```cs
    #region HelloWorld
```
will changed

```cs
    #
    region HelloWorld
```

but it's not correct.

**Comment by Leopotam** [comment]
Should region / endregion respect "styleIndentPreprocessorIgnored" option or always be indented?

**Comment by Leopotam** [comment]
fixed in 0.0.12

**Comment by Leopotam** [comment]
@netpyoung, if it works for you, can you write review at marketplace, please? :)

**Comment by netpyoung** [comment]
why not 😄
