### ISSUE TITLE
Feature request: Only format selected lines

### ISSUE THREAD

**Issue by AlexHankins** [Leopotam/vscode-csharpfixformat#20]
If this feature already exists, could you point me to it?

### C# FixFormat extension version:
0.0.32

### VsCode version:
1.16.0

## Steps to reproduce
Open a poorly formatted file, select some lines, right click, CSharp: Fix format.

## Expected  behavior
It would be awesome and appreciated if it only changed the selected lines.

## Actual behavior
Formats the entire file.

**Comment by Leopotam** [comment]
There are no format for selection and not planned due you cant get valid indentation for selected only lines. In new releases formatter will support automatic code reformatting on file save / copy&paste, so, selection will doesnt matter.
