### ISSUE TITLE
The "cleaner" is erroneously formatting the formated-literal string

### ISSUE THREAD

**Issue by bernardbr** [Leopotam/vscode-csharpfixformat#21]
Hi @Leopotam !

I caught a problem when we have literal strings in source code. This issue  is similar to this one #8 
Thanks!

### C# FixFormat extension version:
0.0.32

### VsCode version:
Version 1.16.0
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-06T16:27:49.891Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## Steps to reproduce

Write a method like this:
```csharp
        protected void Test()
        {
            string[] array = new [] { "A", "B" };
            var x = $@"SELECT {string.Join(",", array)}";
        }
```

Do the clean "Ctrl + Alt + I"

## Expected  behavior

The literal string must be intalterated

## Actual behavior

The string will be:

```csharp
        protected void Test()
        {
            string[] array = new[] { "A", "B" };
            var x = $@"SELECT {string.Join(",
                ", array)}";
        }
```

**Comment by Leopotam** [comment]
@bernardbr can you check develop branch? is issue fixed for you?

**Comment by bernardbr** [comment]
Hello @Leopotam I did this:

Uninstall the public version
git clone -b develop https://github.com/Leopotam/vscode-csharpfixformat.git
Run "npm install" from project folder.
Run "npm run package" from project folder.
Install brand new packed *.vsix (0.0.33) bundle through vscode plugins menu option "Install from VSIX".

But the behavior was the same of the public version...

Here my settings for the extension:
```json
{
    "csharpfixformat.sort.usings.splitGroups": true,
    "csharpfixformat.style.braces.onSameLine": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.activateDefaultFormatterAfter": true
}
```

**Comment by Leopotam** [comment]
@bernardbr btw, why you use csharpfixformat.style.activateDefaultFormatterAfter? You will lose all custom formatting after this (useful only if you want to sort usings). Now it looks like broken when working in last vscode (calling default formatter), this settings will be deprecated when plugin will changed to work as default formatter. Now - better to to remove this settings.
About issue - i cant reproduce it on your example code with your settings (empty file with one method) :(

**Comment by bernardbr** [comment]
@Leopotam I'm using this setting a long time. I'll try to disable this...

I do all the steps that you asked and got the same behavior.

I've created a repo to reproduce the problem.

https://github.com/bernardbr/fixFormat-example

**Comment by Leopotam** [comment]
@bernardbr ok, i see, problem in multiline. Are you sure that you really want this behaviour (with alot of spaces as indents)?

**Comment by bernardbr** [comment]
Unfortunately yes... =(
I'm writing a database provider and using ```$@``` to format the scripts to run on the database.

**Comment by Leopotam** [comment]
@bernardbr looks like it hard to fix it without full ast parsing (now its just alot of regexp postfixes). Ill try to find solution, but no promises. For my use case - better to ban all C# features after fw3.5 ;)

**Comment by bernardbr** [comment]
lol!
Not a problem @Leopotam, in this case, I'll continue to use the comment to prevent the behavior!
Thank you for your attention to this matter! =D

**Comment by Leopotam** [comment]
@bernardbr you can fix current issue if you will remove all internal double quotes (move string.Join() methods outside from interpolated string and use as variables).

**Comment by Leopotam** [comment]
@bernardbr can you check develop branch? is issue fixed for you? da5e5af1005f31654ed4798338b3b1cfc2392e62

**Comment by bernardbr** [comment]
Works perfectly! You're the best!
Thanks...
I got a new issue, can I report here or you prefer a new one?

**Comment by Leopotam** [comment]
@bernardbr if its related thing - here, otherwise - new one.

**Comment by bernardbr** [comment]
I don't know if it is related...

I put a ```where``` for a generic parameter in my class and the formatting won't work fine...

**Comment by Leopotam** [comment]
@bernardbr inside template string? Now all content inside string (due it string :) ) will not be formatted at all, you should fix it by yourself.

**Comment by bernardbr** [comment]
No... Where in class:
```csharp
class Class1<T>
    where T: class
{
...
}
```

I put the example in my repro repo...

**Comment by Leopotam** [comment]
@bernardbr looks like different issue from current one. You can use gists for short code examples, no need to create repos or something like this.

**Comment by bernardbr** [comment]
OK!
I'll open a new one with the example!
