### ISSUE TITLE
The extension does a wrong format when a class with generic parameter has a "where" clause.

### ISSUE THREAD

**Issue by bernardbr** [Leopotam/vscode-csharpfixformat#22]
### C# FixFormat extension version:
0.0.33

### VsCode version:
Version 1.16.0
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-06T16:27:49.891Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## Steps to reproduce
Write a class like this:
```csharp
using System;

using System.Collections.Generic;

namespace example
{
    public class Class1<T>
        where T: class
    {
        /// <summary>
        /// My summary.
        /// </summary>
        /// <returns>The SQL Select.</returns>
        public static string GetSelectScript()
        {
            var tableName = "Table";
            var fields = new List<string>(3);
            fields.Add("first");
            fields.Add("second");
            fields.Add("last");

            var keyName = "key_name";
            var ids = new List<string>(1);
            ids.Add($"{keyName} = @{keyName}");

            return $@"
                SELECT {string.Join(", ", fields)}
                FROM {tableName}
                WHERE {string.Join(" AND ", ids)}
            ";
        }
    }
}
```

## Expected  behavior

The ```{``` keep aligned with ```public class```. This is the default behavior of VisualStudio and VsCode formatter.

## Actual behavior

The ```{``` will be aligned with where and not with ```public class```

**Comment by Leopotam** [comment]
@bernardbr can you check develop branch? is issue fixed for you? 0ed38b861bf31a0de35688b2e8ed037fc9cfb91f

**Comment by bernardbr** [comment]
It works!
Thank you SO much @Leopotam!

**Comment by Leopotam** [comment]
@bernardbr 0.0.33 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by bernardbr** [comment]
Hello @Leopotam!
I caught a situation that I believe is a reflection of this adjustment!

```csharp
using System;

using System.Collections.Generic;

namespace example
{
    public class Class1 : IDisposable
    {
        /// <summary>
        /// My summary.
        /// </summary>
        /// <returns>The SQL Select.</returns>
        public static string GetSelectScript()
        {
            var tableName = "Table";
            var fields = new List<string>(3);
            fields.Add("first");
            fields.Add("second");
            fields.Add("last");

            var keyName = "key_name";
            var ids = new List<string>(1);
            ids.Add($"{keyName} = @{keyName}");

            return $@"
                SELECT {string.Join(", ", fields)}
                FROM {tableName}
                WHERE {string.Join(" AND ", ids)}
            ";
        }
    }
}
```

If you try fix code format the indentation will be wrong.

**Comment by Leopotam** [comment]
@bernardbr fix reverted - some cases were broken, cant fix it fast without AST context. Suggestion: put all constraints on same line:
```
class<T> where T : class
{
}
```
It will work on 0.32 version and 0.34.

**Comment by bernardbr** [comment]
Ok! For now, I'll do it!
Thx!

**Comment by Leopotam** [comment]
Marked as "known issues". :(
