### ISSUE TITLE
Add option to use tabs instead of spaces

### ISSUE THREAD

**Issue by jarommadsen** [Leopotam/vscode-csharpfixformat#23]
### C# FixFormat extension version:
0.0.34

### VsCode version:
1.16.0

## Steps to reproduce
- Open Command Palette
- Run Fix Format command

## Expected  behavior
- Not replace tabs

## Actual behavior
- Replaces tabs with spaces

## Notes:
Please add an option to format using tabs instead of spaces. It would also be nice to determine tab/space size.

**Comment by Leopotam** [comment]
@jarommadsen can you check last state of develop branch (0.0.35)? is issue fixed for you?

**Comment by jarommadsen** [comment]
It's fixed in develop branch! Thanks for the quick response!

**Comment by Leopotam** [comment]
0.0.35 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@jarommadsen if it works for you, can you write review at marketplace, please? :)

**Comment by jarommadsen** [comment]
👍
