### ISSUE TITLE
Disabling space before parenthesis does not work for typeof()

### ISSUE THREAD

**Issue by moskal91** [Leopotam/vscode-csharpfixformat#24]
## Steps to reproduce
1. Add configuration option:
```json
"csharpfixformat.style.spaces.beforeParenthesis": false
```
2. Type code:
```csharp
Debug.Log(typeof(SomeClass));
```
3. Launch C# FixFormat
## Expected  behavior
Code formatted as (no change):
```csharp
Debug.Log(typeof(SomeClass));
```

## Actual behavior
Code formatted as (space after `typeof`):
```csharp
Debug.Log(typeof (SomeClass));
```

**Comment by Leopotam** [comment]
@moskal91 can you check last state of develop branch (0.0.36)? is issue fixed for you?

**Comment by Leopotam** [comment]
no feedback, closed as fixed. 0.0.36 version released on marketplace.

**Comment by moskal91** [comment]
@Leopotam Awesome, I had not expected such fast response. It is working now, thanks!
