### ISSUE TITLE
Proposition: set "csharpfixformat.style.braces.onSameLine: false" by default

### ISSUE THREAD

**Issue by seoriy** [Leopotam/vscode-csharpfixformat#25]
subj. Because it's more common practice to put open brace on a new line rather than on the same line. 
class Test
{
  // for example
}

**Comment by Leopotam** [comment]
Its not "more common" practice, but project dependent settings. For example, [mono project](https://github.com/mono/mono) use braces on same line. Is your project larger than mono?

**Comment by seoriy** [comment]
Off-course it depend on project's code convention. But if you look at code examples in msdn or Microsoft code conventions or .NET Framework sources - there is common to use braces from new line for classes, struct, blocks, etc. Look inside .NET Core sources also, and ASP.NET, Entity Framework, etc
Is Mono larger than .NET Framework? I don't think so.
Look at other most famous projects like NLog, Newton.Json, xUnit, NUnit, Ninject, Dapper, MassTransit and many-many other - there also rule "braces on a new line" is most used!
This rule is used in Visual Studio by default.
Same for the Resharper.
And the same for any .NET project I was worked with in my whole career.
Is that enough arguments to make you believe me, what in .NET world (not JavaScript) putting braces on a new line - is a common practice?)

**Comment by Leopotam** [comment]
1. It will break default settings for all guys who installed this plugin before (63570 installs nowadays).
2. Its my default codestyle for multiple projects.
3. You can change settings all settings as you want and create your own style (and share to teammates through .vscode folder sharing / putting it to repo).
Or you can use default omnisharp formatter - its from microsoft guys who works on roslyn / .net core and who knows how code should be formatted.

**Comment by seoriy** [comment]
1. Okay, this is an argument
4. Hm, seems like he is from Unity3D/Mono world too... I'm wondering, where did you guys got that convention? Even in examples in Mono and Unity3D docs rule "brace on new line" used too - http://www.mono-project.com/docs/getting-started/mono-basics/ or https://unity3d.com/ru/learn/tutorials/topics/scripting/activating-gameobjects?playlist=17117 i.e.

**Comment by Leopotam** [comment]
@seoriy you can even fork this repo and tweak it as you want - its how opensource works. For this repo default settings will be inited as is.
