### ISSUE TITLE
Number suffixes formatting

### ISSUE THREAD

**Issue by Siccity** [Leopotam/vscode-csharpfixformat#27]
Unity has a builtin class named Matrix4x4.
My line of code `Matrix4x4 m = GUI.matrix;` gets formatted into `Matrix4x4m = GUI.matrix;`
![image](https://user-images.githubusercontent.com/6402525/31573418-91287aee-b0bb-11e7-92c9-3a7fd505bbca.png)

**Comment by Leopotam** [comment]
@Siccity can you check last state of develop branch? is issue fixed for you?

**Comment by Siccity** [comment]
That fixed the original issue but spawned a new.
This time it's the float values.
![image](https://user-images.githubusercontent.com/6402525/31577488-b74d8c38-b10f-11e7-95fc-e5dd6ae9dc6f.png)

**Comment by Leopotam** [comment]
@Siccity can you check last state of develop branch again?

**Comment by Siccity** [comment]
It seems to work now.

**Comment by Leopotam** [comment]
@Siccity 0.0.37 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Siccity** [comment]
Following this update i encountered a new bug which might be related:
![image](https://user-images.githubusercontent.com/6402525/31588333-a02f9640-b1f0-11e7-863b-b40473cfc87e.png)

**Comment by Leopotam** [comment]
@Siccity can you check last state of develop branch?

**Comment by Siccity** [comment]
That seems to have fixed it.

**Comment by Leopotam** [comment]
@Siccity any new issues relative to this fix?

**Comment by Siccity** [comment]
Not from what I can see. I ran FixFormat on a bunch of my scripts and it seems to work fine in all cases. If i run into something I'll notify you.

**Comment by Leopotam** [comment]
@Siccity 0.0.38 released on official marketplace, you can uninstall custom package and install public release.
