### ISSUE TITLE
Keybinding on macOS

### ISSUE THREAD

**Issue by bgdnr** [Leopotam/vscode-csharpfixformat#28]
C# FixFormat extension version: 0.0.38
VsCode version: 1.17.2

Is there a key biding for Visual Studio Code on macOS?
From the details notes I can see that on Windows it's ctrl+alt+i, however this shortcut is not applicable on mac.

**Comment by Leopotam** [comment]
@bgdnr my main platform is osx, so, its applicable. You can name "alt" as "option", but even on apple keyboard there is "alt" label.

**Comment by bgdnr** [comment]
Hmmm...that's strange. I swear it didn't worked a few minutes ago. Anyway, thanks for the reply.
