### ISSUE TITLE
command 'csharpfixformat.process' not found

### ISSUE THREAD

**Issue by wulei** [Leopotam/vscode-csharpfixformat#29]
### C# FixFormat extension version:
v0.0.39

### VsCode version:
1.18.0

## Actual behavior

command 'csharpfixformat.process' not found

**Comment by Leopotam** [comment]
@wulei read description at README.md - now extension works as default FormatProvider and uses default hotkeys / command for format document / format on save, on paste, on type, etc - no more custom hotkeys / commands.
