### ISSUE TITLE
Breaks interpolated strings

### ISSUE THREAD

**Issue by fergalmoran** [Leopotam/vscode-csharpfixformat#3]
Nice plugin, one small issue. It adds a space after the $ in interpolated strings

`var foo = $"Hello {sailor}";`
becomes
`var foo = $ "Hello {sailor}";`

causing a compilation error.

**Comment by Leopotam** [comment]
fixed in 0.0.13.

**Comment by Leopotam** [comment]
@fergalmoran, if it works for you, can you write review at marketplace, please? :)

**Comment by fergalmoran** [comment]
Works perfectly @Leopotam - thanks for the quick turnaround.
