### ISSUE TITLE
spaces.beforeParenthesis:false takes priority over spaces.afterParenthesis:true

### ISSUE THREAD

**Issue by apkd** [Leopotam/vscode-csharpfixformat#31]
### C# FixFormat extension version:
0.0.39
### VsCode version:
1.17.2

## Steps to reproduce
Use the following settings:
```json
"csharpfixformat.style.spaces.beforeParenthesis": false,
"csharpfixformat.style.spaces.afterParenthesis": true
```
This is intended to simulate the default VS2017 C# formatting.

## Expected behavior
```c#
if (true) x = false;
if (true) (x) = false;
if (item is Renderer) (item as Renderer).enabled = false;
```

## Actual behavior
```c#
if (true) x = false;
if (true)(x) = false;
if (item is Renderer)(item as Renderer).enabled = false;
```

**Comment by Leopotam** [comment]
@apkd 
> "csharpfixformat.style.spaces.afterParenthesis": true
Its default value

> "csharpfixformat.style.spaces.beforeParenthesis": false,
Did you tried without this setting (true by default)? Looks like what you want.

**Comment by apkd** [comment]
@Leopotam 
Setting `csharpfixformat.style.spaces.beforeParenthesis` to true results in other inconsistencies with the default VS2017 formatting style (eg. space before argument list in method calls). I find it that this is the style most often used by C# programmers (also in Microsoft documentation and samples, as well as the .NET reference source itself) so it probably should be replicable, if not the default.
Fantastic job on the extension by the way; it's pretty much indispensable.

**Comment by Leopotam** [comment]
@apkd so, how should be formatted `var t = ((10))` (is space between last ")" should be there) and `var t = ((10)), s = 1` (is space before "," should be there)?

**Comment by Leopotam** [comment]
@apkd its not `spaces.beforeParenthesis` issue, but `spaces.afterParenthesis` with any next non alphanumeric char. Can you check last state of develop branch? is issue fixed for you?

**Comment by apkd** [comment]
It seems that fixes the issue. Thanks!

**Comment by Leopotam** [comment]
@apkd 0.0.41 released on official marketplace, you can uninstall custom package and install public release. if this extension useful for you, can you write review at marketplace, please? :)
