### ISSUE TITLE
"No csharp formatter installed"

### ISSUE THREAD

**Issue by Siccity** [Leopotam/vscode-csharpfixformat#32]
This started happening right after updating vscode. It had been working fine until then.

### C# FixFormat extension version:
v0.0.42

### VsCode version:
1.18.0

## Steps to reproduce
`alt+shift+f`

## Expected  behavior
Format file

## Actual behavior
![billede](https://user-images.githubusercontent.com/6402525/32883451-bea2deea-cab7-11e7-8d16-8985d038c8f4.png)

**Comment by NakOh** [comment]
Me too -> If you use OmniSharp,  Setting Perference

  // Enable/disable default C# formatter (requires restart).
  "csharp.format.enable": true,

But this only 

void Start()
{
}

I want 

void Start(){
}

.. Maybe Bug

**Comment by Leopotam** [comment]
@Siccity very strange behaviour - looks like vscode dont allow to register and react on language at same plugin with standard activation events. I'll try to find way to fix it, but now you can just install official omnisharp c# extension from microsoft - it will register "csharp" language for all other extensions and all will work as must.

@NakOh this issue appears only when no other C# plugins installed in vscode.

**Comment by NakOh** [comment]
@Leopotam Yes, I installed omnisharp and fixed C# Format. But 

I command "editor.action.formatDocument".

But Just

void Start()
{
}

No 

void Start(){
}

I tried to change preference.. but did not work.

**Comment by Leopotam** [comment]
@NakOh wait, you installed omnisharp, installed c#fixformat, reloaded vscode, on first start c#fixformat said - you should set csharp.format.enable=false, you agreed, right? then all should works.

**Comment by NakOh** [comment]
If I set csharp.format.enable = false, it has same Problem. 

![image](https://user-images.githubusercontent.com/7420198/32886908-96f6b814-cb05-11e7-9f79-e231a24d1f89.png)

**Comment by Leopotam** [comment]
@NakOh omnisharp extension installed?

**Comment by NakOh** [comment]
<img width="772" alt="2017-11-16 7 47 08" src="https://user-images.githubusercontent.com/7420198/32887376-0fa44118-cb07-11e7-89b3-989bfda23d80.png">

this?

**Comment by Leopotam** [comment]
@Siccity @NakOh looks like i found problem, will wix it in next version.

**Comment by Leopotam** [comment]
@Siccity @NakOh can you check last state of develop branch? is issue fixed for you?

**Comment by Siccity** [comment]
Yes! Works for me now :)

**Comment by Leopotam** [comment]
@Siccity 0.0.43 released on official marketplace, you can uninstall custom package and install public release. thanks.
