### ISSUE TITLE
Expression-bodied members disallow expression body on next line

### ISSUE THREAD

**Issue by apkd** [Leopotam/vscode-csharpfixformat#34]
### C# FixFormat extension version:
0.0.43

### VsCode version:
1.18.1

## Expected  behavior
Formatting the following code should not result in any formatting changes:
```csharp
sealed class T
{
	string a1() => "";

	string a2()
	=> "";

	string a3()
		=> "";

	string a4() =>
	"";

	string a5() =>
		"";

	string b1 => "";

	string b2
	=> "";

	string b3
		=> "";

	string b4 =>
	"";

	string b5 =>
		"";
}
```
The Visual Studio 2017 formatter leaves indentation in this case to the programmer. I personally think same-line, next-line and next-line indented are all valid options. The same-line or next-line arrow placement is a matter of preference too.

## Actual behavior
Some expression bodies are (inconsistently) moved to the line with the member name. Indentation is lost.

```csharp
sealed class T
{
	string a1() => "";

	string a2() => "";

	string a3() => "";

	string a4() =>
		"";

	string a5() =>
		"";

	string b1 => "";

	string b2
		=> "";

	string b3
		=> "";

	string b4 =>
		"";

	string b5 =>
		"";
}
```

**Comment by Leopotam** [comment]
@apkd 

> The Visual Studio 2017 formatter leaves indentation in this case to the programmer.
In current implementation only new expression can be placed at same indentation with previous one, otherwise all parts of of not completed expression will be placed on +1 indentation:
```
var a = 10 +
    20 +
    30;
var b = 10 + 20 + 30;
```
Without real c# AST parser "expression-bodied members" will be parsed as standard expression.
