### ISSUE TITLE
Inconsistent/invalid formatting of optional method arguments

### ISSUE THREAD

**Issue by apkd** [Leopotam/vscode-csharpfixformat#35]
### C# FixFormat extension version:
0.0.43

### VsCode version:
1.18.1

## Expected  behavior
No space after named argument name:

```csharp
sealed class T
{
	const int number = 0;
	const string text = "";

	string a1(int argName) => "";

	string a2() => a1(argName: 0);

	string a3() => a1(argName: number);

	string b1(string argName) => "";

	string b2() => b1(argName: "");

	string b3() => b1(argName: text);
}
```

## Actual behavior
Invalid space before the `:` character depending on kind of provided argument. Only string literal arguments are formatted correctly.

```csharp
sealed class T
{
	const int number = 0;
	const string text = "";

	string a1(int argName) => "";

	string a2() => a1(argName : 0);

	string a3() => a1(argName : number);

	string b1(string argName) => "";

	string b2() => b1(argName: "");

	string b3() => b1(argName : text);
}
```

By the way, should I keep those issues coming as I encounter more edge cases like this one?

**Comment by Leopotam** [comment]
I think i should update description of extension that it will never support new features after C#3.5. :)

**Comment by apkd** [comment]
I see, I'm just posting all issues I encountered to see if any of them can be fixed with relative ease :) Feel free to close any issues you determined to be impossible/too much work to implement.

**Comment by Leopotam** [comment]
@apkd can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@apkd no feedback, closed as fixed. 0.0.44 version released on marketplace.
