### ISSUE TITLE
Invalid #region indentation when tab uses

### ISSUE THREAD

**Issue by Kloeve** [Leopotam/vscode-csharpfixformat#38]
### C# FixFormat extension version:
0.0.45

### VsCode version:
1.18.1

## Steps to reproduce
Using format document on c# files, with "csharpfixformat.style.indent.regionIgnored" set to true or false, doesn't seem to make a difference. Regions are indentet either way.

## Expected  behavior
```csharp
public class House {
#region CONSTANTS
    public const float someValue = 10F;
#endregion
}
```

## Actual behavior
```csharp
public class House {
    #region CONSTANTS
    public const float someValue = 10F;
    #endregion
}
```

**Comment by Leopotam** [comment]
@Kloeve cant reproduce issue on new file with your code only, looks like it side effect of something around this code block.

**Comment by Kloeve** [comment]
Thanks for trying it.

I've done some more testing, and the odd part is that it doesn't seem to happen to any c# file i've created in VS Code, but only with the files i've create through Unity3D. (I realise that's likely not what you use VS Code for, but it's worth mentioning.)

I've stripped down a project (with settings), to two simple cSharp files called Works.cs and WorksNot.cs, where one script formats correctly and the other does not. I can't see any differences between the two files. (Other than naming, of course.)

[SampleProject.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1521293/SampleProject.zip)

**Comment by Kloeve** [comment]
There might be no need for the sample project.

It seems the file that works is set to "Spaces: 4" in the rigth lower corner.

Where the one that doesn't work is set to Tab Size: 4. If i change it to Spaces: 4 it works as expected.

I can solve it with that for now, but shouldn't it work no matter what indentation i use?

**Comment by Leopotam** [comment]
@Kloeve problem not in size of indentation in spaces, but in using tabs as indentation char. "Works"-file uses spaces, "NotWorks" uses tabs. Looks like vscode dont use automatic correction even on 
```
set "editor.insertSpaces": true,
"editor.detectIndentation": false,
```
settings, i will think about it.

**Comment by Leopotam** [comment]
@Kloeve can you check last state of develop branch? is issue fixed for you?

**Comment by Kloeve** [comment]
It seems to work in both my actually project and the sample one.

You continue to be a wizard at bug solving. Thanks Leopotam~!

**Comment by Leopotam** [comment]
0.0.46 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@Kloeve if this extension useful for you, can you write review at marketplace, please? :)
