### ISSUE TITLE
Bitwise assignment operators Indentation

### ISSUE THREAD

**Issue by MarcPerezAtelierMirari** [Leopotam/vscode-csharpfixformat#39]
## Environment data
"<<=" left shift assignment
">>=" right shift assignment
### C# FixFormat extension version:
v0.0.45

### VsCode version:
VsCode Insiders 1.19.0 x64

    "csharp.format.enable": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,

## Steps to reproduce
Indent (ctrl + K, ctrl + F) a "<<=" or ">>=".

## Expected  behavior

        int one = 1;
        one <<= 1;
        one >>= 1;
        return one;

## Actual behavior

        int one = 1;
        one << = 1;
        one >> = 1;
        return one;

**Comment by Leopotam** [comment]
@MarcPerezAtelierMirari can you check last state of develop branch? is issue fixed for you?

**Comment by MarcPerezAtelierMirari** [comment]
I just tried the develop branch and it works ^^

**Comment by Leopotam** [comment]
0.0.46 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@MarcPerezAtelierMirari if this extension useful for you, can you write review at marketplace, please? :)
