### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by skryshi** [Leopotam/vscode-csharpfixformat#4]
Thank you for making this plugin!

I have a feature request. Some C# formatting by OmniSharp is wonky. Take a look at this snippet:

T data =
        default (T);
      yield
      return null;

It's got four lines instead of two. This is how it's ought to format:

T data = default (T);
yield return null;

Is this something you can add to the plugin?

**Comment by Leopotam** [comment]
@skryshi can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
fixed in 0.0.15.

**Comment by Leopotam** [comment]
@skryshi can you confirm that issue fixed in 0.0.15?

**Comment by skryshi** [comment]
Confirm. Thank you for quick turnaround!

**Comment by Leopotam** [comment]
@skryshi if this extension useful for you, can you write review at marketplace, please? :)

**Comment by skryshi** [comment]
Done )
