### ISSUE TITLE
I have trouble formatting

### ISSUE THREAD

**Issue by NakOh** [Leopotam/vscode-csharpfixformat#40]
### C# FixFormat extension version:
0.0.46

### VsCode version:
1.18.1

## Steps to reproduce
I have

<img width="464" alt="2017-12-05 3 23 00" src="https://user-images.githubusercontent.com/7420198/33592876-3516ed74-d9d0-11e7-9fdf-13b1ebaa9205.png">

## Expected  behavior

I don't want to fix format "\n".. 

## Actual behavior

If i fix format 

<img width="818" alt="2017-12-05 3 23 47" src="https://user-images.githubusercontent.com/7420198/33592904-5322f84e-d9d0-11e7-804b-7eff87c6e4b2.png">

What should i do?

**Comment by Leopotam** [comment]
@NakOh cant reproduce it on simple code:
```
var t = "";
t += "\n" + s;
t += "\n" + s;
t += "\n}";
```
looks like its side effect of code around this block (non-balanced braces / double quotes). can you provide invalid file?

**Comment by NakOh** [comment]
[AutoProgramedScript.cs.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1530337/AutoProgramedScript.cs.zip)

Here

**Comment by Leopotam** [comment]
@NakOh ok, strange behaviour on combination of:
```
t += s + "{\n";
for (var i = 0; i< 1; i++) { }
t += "\n" + s;
```
will try to fix it.

**Comment by Leopotam** [comment]
@NakOh can you check last state of develop branch? is issue fixed for you?

**Comment by NakOh** [comment]
Good! Nice work! Thank you

**Comment by Leopotam** [comment]
@NakOh 0.0.47 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@NakOh if this extension useful for you, can you write review at marketplace, please? :)

**Comment by NakOh** [comment]
Of Course~
