### ISSUE TITLE
I have trouble

### ISSUE THREAD

**Issue by NakOh** [Leopotam/vscode-csharpfixformat#41]
### C# FixFormat extension version:
0.0.50

### VsCode version:
1.18.1

## Steps to reproduce
![1](https://user-images.githubusercontent.com/7420198/33817208-aa1ffa24-de81-11e7-9a5d-5246feb00fce.PNG)

## Expected  behavior
I don't know

## Actual behavior
Maybe Fix Format Bug

[VST_Main.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1546660/VST_Main.zip)
- Here is My code

**Comment by Leopotam** [comment]
@NakOh just add blank line between methods - it will fix all issues:
```
        [MenuItem ("VST / Show")]
        private static void ShowWindow () {
            Init ();
        }

        [MenuItem ("VST / ForceCompile")]
        private static void ForceCompile () {
            AssetDatabase.Refresh ();
        }

        [MenuItem ("VST / Clear")]
        private static void ClearScene () { }
```

**Comment by Leopotam** [comment]
@NakOh 0.0.51 released on official marketplace, this issue should be auto-fixed in it.

**Comment by NakOh** [comment]
Thank you
