### ISSUE TITLE
Newline added between attributes

### ISSUE THREAD

**Issue by LavaPatrik** [Leopotam/vscode-csharpfixformat#42]
## Environment data
The following started happening after I updated to v0.0.51
## Steps to reproduce
Update C# FixFormat to v0.0.51
Create a new cs file with the following contents:
```cs
using NUnit.Framework;

[TestFixture]
public class TestClass
{
    [TestCase(50)]
    [TestCase(2000)]
    [TestCase(960)]
    [TestCase(1024)]
    [TestCase(2048)]
    [TestCase(3000)]
    public void MyTest(int someInt)
    {
        Assert.That(someint, Is.GreaterThan(0));
    }
}
```
Save file and let it auto format

## Expected  behavior
The file should look like this
```cs
using NUnit.Framework;

[TestFixture]
public class TestClass
{
    [TestCase(50)]
    [TestCase(2000)]
    [TestCase(960)]
    [TestCase(1024)]
    [TestCase(2048)]
    [TestCase(3000)]
    public void MyTest(int someInt)
    {
        Assert.That(someint, Is.GreaterThan(0));
    }
}
```

## Actual behavior
But the file looks like this instead
```cs
using NUnit.Framework;

[TestFixture]
public class TestClass
{

    [TestCase(50)]

    [TestCase(2000)]

    [TestCase(960)]

    [TestCase(1024)]

    [TestCase(2048)]

    [TestCase(3000)]
    public void MyTest(int someInt)
    {
        Assert.That(someint, Is.GreaterThan(0));
    }
}
```

**Comment by NiklasBorglund** [comment]
I have this problem too, and it makes classes with multiple attributes very much less readable.  Please let us know how we can reach a solution.

**Comment by Leopotam** [comment]
@LavaPatrik @NiklasBorglund will fix it in next few hours.

**Comment by LavaPatrik** [comment]
{
    "editor.fontSize": 18,
    "window.zoomLevel": 0,
    "editor.codeLens": false,
    "editor.wordWrap": false,
    "editor.minimap.enabled": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.meta": true,
        "**/*.*.meta": true,
        "**/*.unity": true,
        "**/*.unityproj": true,
        "**/*.mat": true,
        "**/*.fbx": true,
        "**/*.FBX": true,
        "**/*.tga": true,
        "**/*.cubemap": true,
        "**/*.prefab": true,
        "**/Library": true,
        "**/ProjectSettings": true,
        "**/Temp": true
    },
    "editor.formatOnSave": true,
    "csharpfixformat.style.braces.onSameLine": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,
    "csharpfixformat.style.spaces.beforeBracket": false,
    "csharpfixformat.style.spaces.afterBracket": false,
    "csharpfixformat.sort.usings.systemFirst": true,
    "files.autoSave": "afterDelay",
    "workbench.activityBar.visible": true,
    "git.enableSmartCommit": true,
    "csharp.format.enable": false
}

**Comment by Leopotam** [comment]
@LavaPatrik @NiklasBorglund if you need solution right now and can't wait - you can download sources of 0.0.50 release and build local vsix package.

**Comment by LavaPatrik** [comment]
It's not super urgent, more of an annoyance. But thanks!

**Comment by Leopotam** [comment]
@LavaPatrik can you check last state of develop branch? is issue fixed for you?

**Comment by LavaPatrik** [comment]
Yes, I just tried it and it works! Thank you!

**Comment by Leopotam** [comment]
@LavaPatrik 0.0.52 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@LavaPatrik if this extension useful for you, can you write review at marketplace, please? :)
