### ISSUE TITLE
Format all C# files formats with spaces instead of tabs.

### ISSUE THREAD

**Issue by StewMcc** [Leopotam/vscode-csharpfixformat#43]
### C# FixFormat extension version:
0.0.52

### VsCode version:
1.19

## Steps to reproduce
 - Right click folder
 - click "C#FixFormat: fix C# files"
## Expected  behavior
Format all files with similar behaviour to format document.

## Actual behavior
Formats document with spaces instead of tabs.

## Notes 
Similiar to https://github.com/Leopotam/vscode-csharpfixformat/issues/23 but when formating folder. Formatting individual files works correctly. 
Appears to not honor .editorconfig settings when formatting all files, but does when editing individually?

**Comment by Leopotam** [comment]
@StewMcc well, it should works with same settings as individual one. I can suggest to disable autodetection of indentation type and force use spaces:
```
"editor.detectIndentation": false,
"editor.insertSpaces": true,
```

**Comment by StewMcc** [comment]
Editing these settings still ends up with format all ignoring the .editorconfig settings, which it seems to honor when using "Format Document". 

Find it odd that it worked on individual format documents, but not on format all?

**Comment by Leopotam** [comment]
@StewMcc no, any external configs are ignored by extension, only vscode settings in use (global or per workspace at .vscode folder). I mean - I dont know, maybe vscode respect .editorconfig files internaly, I request vscode for user settings through api.

**Comment by StewMcc** [comment]
Fair enough, odd one, will just not use format all, guess it must be something in vscode editorconfig that is changing it but still allows it to use your fix's. Awesome plugin anyway!
