### ISSUE TITLE
Support for Object Initializer indent

### ISSUE THREAD

**Issue by yhvicey** [Leopotam/vscode-csharpfixformat#44]
## Expected  behavior

```
StudentName student2 = new StudentName
{
    FirstName = "Craig",
    LastName = "Playstead",
};
```

## Actual behavior

```
StudentName student2 = new StudentName
{
FirstName = "Craig",
LastName = "Playstead",
};
```

**Comment by Leopotam** [comment]
@yhvicey cant reproduce issue with your code example, both styles "braces.onSameLine"=true and braces.onSameLine=false formatting correctly. Looks like side effects from code around. If you want to format nested initializators - no, its not supported.

**Comment by Leopotam** [comment]
@yhvicey issue closed, will be reopened after new info will be provided.

**Comment by LordColus** [comment]
I'm having the same problem. 
VSCode: v 1.18.0
C# FixFormat: v 0.0.53

Settings: 
`"csharp.format.enable": false,`
`"csharpfixformat.style.braces.onSameLine": false,`
`"csharpfixformat.style.spaces.beforeParenthesis": false,`
`"editor.formatOnSave": true`

**Comment by Leopotam** [comment]
@LordColus can you provide cs-file with example code where I can reproduce issue?

**Comment by LordColus** [comment]
Ok, this is bizarre.
![screen shot 2018-01-06 at 3 12 58 pm](https://user-images.githubusercontent.com/29384525/34644001-3bbcbd56-f2f4-11e7-9182-90a8af9aa6f0.png)
![screen shot 2018-01-06 at 3 13 16 pm](https://user-images.githubusercontent.com/29384525/34644002-405ecb6a-f2f4-11e7-9f1e-00cd6cd09ffd.png)

It only formats weird when the test string is commented or not there.

**Comment by LordColus** [comment]
I removed the field in my original file and the formatter started working again.

**Comment by Leopotam** [comment]
@LordColus can you edit your post with textual version, please? You can paste your code here with wrap it with ``` or use https://gist.github.com

**Comment by LordColus** [comment]
Sorry! Here it is:
```
using System;

public class Person
{
    public int Id { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
}

public class Program
{

    string test = "test";

    public static void Main()
    {
        Person person1 = new Person
        {
        Id = 1,
        FName = "John",
        LName = "Smith"
        };

        Person person2 = new Person
        {
            Id = 2,
            FName = "Sally",
            LName = "Johnson"
        };
    }
}
```

**Comment by Leopotam** [comment]
@LordColus can you check last state of develop branch? is issue fixed for you?

**Comment by LordColus** [comment]
The dev branch did not fix it.

**Comment by Leopotam** [comment]
@LordColus are you sure that you tested develop branch instead of master? Version should be 0.0.54.

**Comment by LordColus** [comment]
Yes, version is 0.0.54; has not fixed it.

**Comment by Leopotam** [comment]
@LordColus its strange, because i cant reproduce issue on your code and with your settings again. What if you will add something to file and save it to force reformat?

**Comment by LordColus** [comment]
When forced to format, it still doesn't indent.

**Comment by Leopotam** [comment]
@LordColus to be sure - can you uninstall all c#fixformat extension versions (remove, reload vscode, if exists - repeat) and try this:
[csharpfixformat-0.0.54.vsix.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1609261/csharpfixformat-0.0.54.vsix.zip)

**Comment by LordColus** [comment]
That works!

**Comment by Leopotam** [comment]
@LordColus it means that you did something wrong with code from develop branch :)

nevermind, 0.0.54 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@LordColus if this extension useful for you, can you write review at marketplace, please? :)

**Comment by LordColus** [comment]
Will do! Thanks for the fix!

**Comment by yhvicey** [comment]
Sorry for being busy these days. I'm formatting code like these:
```csharp
var persons = new List<Person>()
{
    new Person
    {
    Name = "Foo",
    Age = 1,
    },
    new Person
    {
    Name = "Bar",
    Age = 2,
    },
};
```
And it can't be formatted with correct indent. Is this nested initializators? I'm not native speaker and not familiar with these concepts.

VSCode version: 1.19.1
Ext version: 0.0.54

**Comment by Leopotam** [comment]
@yhvicey read readme, please.

**Comment by yhvicey** [comment]
Alright, my fault. Found another little bug and create a new issue: #46
