### ISSUE TITLE
Do-while loops always format with opening brace on same line.

### ISSUE THREAD

**Issue by clt829** [Leopotam/vscode-csharpfixformat#45]
## Environment data
Windows 10 Pro 1709 16299.125

### C# FixFormat extension version:
Version 0.0.52

### VsCode version:
Version 1.19.1

## Steps to reproduce
* Create a C# file with a `do { } while();` loop
* Set "csharpfixformat.style.braces.onSameLine": false
* Format document with Alt-Shift-F

## Expected  behavior
```csharp
do
{
    // statments
} while (true);
```

## Actual behavior
```csharp
do {
    // statments
} while (true);
```

**Comment by Leopotam** [comment]
@clt829 can you check last state of develop branch? is issue fixed for you?

**Comment by clt829** [comment]
Issue is fixed in develop branch 0.0.53
-Thanks!

**Comment by Leopotam** [comment]
@clt829 0.0.53 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@clt829 if this extension useful for you, can you write review at marketplace, please? :)
