### ISSUE TITLE
Method call on nullable value get formatted incorrect sometimes

### ISSUE THREAD

**Issue by yhvicey** [Leopotam/vscode-csharpfixformat#46]
### C# FixFormat extension version:
0.0.54

### VsCode version:
1.19.1

## Steps to reproduce
Declare a type and create a list of its object, then use `FirstOrDefault` method and access its property by '?.' operator
```csharp
class SomeType
{
    public int Id { get; set; }
    public string Content { get; set; }
}
```

## Expected  behavior
```csharp
string SomeMethod(string str)
{
    var someCollection = new List<SomeType>();
    return someCollection.FirstOrDefault(someName => someName.Id == 0)?.Content;
}
```

## Actual behavior
```csharp
string SomeMethod(string str)
{
    var someCollection = new List<SomeType>();
    return someCollection.FirstOrDefault(someName => someName.Id == 0) ? .Content;
}
```

**Comment by Leopotam** [comment]
@yhvicey can you check last state of develop branch? is issue fixed for you?

**Comment by yhvicey** [comment]
Fixed. Thank you!

**Comment by Leopotam** [comment]
@yhvicey 0.0.55 released on official marketplace, you can uninstall custom package and install public release. thanks.
