### ISSUE TITLE
Hash sign in custom warnings is being formatted to their own line, breaking the warning

### ISSUE THREAD

**Issue by LavaNiklas** [Leopotam/vscode-csharpfixformat#47]
## Steps to reproduce
Create a new cs file with the following contents:
```csharp
public class MyClass
{
    #warning This is my warning!
    public void MyMethod()
    {
        
    }
}
```
Save file and let it auto format.

These are my fixformat settings:
```json
"csharpfixformat.style.braces.onSameLine": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,
    "csharpfixformat.style.spaces.beforeBracket": false,
    "csharpfixformat.style.spaces.afterBracket": false,
    "csharpfixformat.sort.usings.enabled": true,
    "csharpfixformat.sort.usings.systemFirst": true,
    "csharpfixformat.style.newline.maxAmount": 0,
```
## Expected  behavior
The file should look like this
```csharp
public class MyClass
{
    #warning This is my warning!
    public void MyMethod()
    {
        
    }
}
```
## Actual behavior
But the file looks like this instead
```csharp
public class MyClass
{#
    warning This is my warning!
        public void MyMethod()
        {

        }
}
```

**Comment by Leopotam** [comment]
@LavaNiklas can you check last state of develop branch? is issue fixed for you?

**Comment by LavaNiklas** [comment]
@Leopotam Yes, it works when I build it from develop - 0.0.56. Thanks!

**Comment by Leopotam** [comment]
@LavaNiklas 0.0.56 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@LavaNiklas if this extension useful for you, can you write review at marketplace, please? :)

**Comment by LavaNiklas** [comment]
@Leopotam Yup, you already have a 5 star review from me there :)
