### ISSUE TITLE
Indentation broken by interpolated strings containing escaped braces

### ISSUE THREAD

**Issue by fernandokm** [Leopotam/vscode-csharpfixformat#48]
### C# FixFormat extension version:
0.0.56

### VsCode version:
1.19.2

## Steps to reproduce
1. Create a file with the following contents:
```csharp
namespace A {
    public class C {
        public void Main () {
            var a = $"{{";
        }
    }
}
```
2. Format the file.

## Expected  behavior
The file should not change:

```csharp
namespace A {
    public class C {
        public void Main () {
            var a = $"{{";
        }
    }
}
```

## Actual behavior
Four extra spaces are inserted before the line `var a = $"{{"`:

```csharp
namespace A {
    public class C {
        public void Main () {
                var a = $"{{";
        }
    }
}
```

This issue can be exacerbated by changing the namespace from `A` to `A.B`, in which case the following result is obtained after formatting (lines 2-4 have extra indentation):

```csharp
namespace A.B {
        public class C {
            public void Main () {
                    var a = $"{{";
        }
    }
}
```

**Comment by Leopotam** [comment]
@fernandokm can you check last state of develop branch? is issue fixed for you?

**Comment by fernandokm** [comment]
It's working now. Thanks!

**Comment by Leopotam** [comment]
@fernandokm 0.0.57 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@fernandokm if this extension useful for you, can you write review at marketplace, please? :)
