### ISSUE TITLE
Spaces are automatically inserted before flow control parenthesis

### ISSUE THREAD

**Issue by jeffreyschoch** [Leopotam/vscode-csharpfixformat#49]
### C# FixFormat extension version:
v0.0.57

### VsCode version:
v1.19.2

## Steps to reproduce
Set false the "csharpfixformat.style.spaces.beforeParenthesis" setting. Write any C# flow control block (if, for, while, etc).  Apply auto-formatting of the document, observe the space before the opening parentheses.

## Expected  behavior
Setting "csharpfixformat.style.spaces.beforeParenthesis" to false will disable spaces from being automatically inserted before any parenthesis, including flow control.

## Actual behavior
With the setting disabled, spaces aren't inserted after function calls and signatures, but are still inserted after flow control blocks.

**Comment by Leopotam** [comment]
@jeffreyschoch it will break compatibility - flow control spaces - part of common style. What if new property will be added about this use case?

**Comment by jeffreyschoch** [comment]
@Leopotam I see. Yes if you're willing to add a new setting to override the common style, that would also solve the issue for me. Thanks for the quick response, let me know if you need any more info about this.

**Comment by Leopotam** [comment]
@jeffreyschoch can you check last state of develop branch? is issue fixed for you? 
"style.spaces.removeAfterCommands" option was added.

**Comment by jeffreyschoch** [comment]
I just downloaded and installed the dev branch version.  I see the new setting, and configured it as such:
![capture](https://user-images.githubusercontent.com/10616707/35350702-c1bccf1a-010c-11e8-98e6-efdc8448ead7.PNG)

I'm not seeing any changes to the auto-format action, spaces are still inserted before the given commands.

**Comment by Leopotam** [comment]
@jeffreyschoch
> spaces are still inserted before

before? you asked about removing space **after** commands. can you share extension version from vscode extension panel?

**Comment by jeffreyschoch** [comment]
@Leopotam Sorry that was a typo, in my mind these spaces are "before parenthesis", but yes also after the command keywords.

**Comment by Leopotam** [comment]
@jeffreyschoch can you remove previous installation and check this one?
[csharpfixformat-0.0.58.vsix.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1661253/csharpfixformat-0.0.58.vsix.zip)

**Comment by jeffreyschoch** [comment]
@Leopotam That vsix version works correctly, the applied formatting removes the spaces after the commands.

The only remaining issue is in the case of commands like "using" which can be used in a context with parenthasis, and without. The currently implementation doesn't handle that:

![example](https://user-images.githubusercontent.com/10616707/35351279-6ad66fce-010e-11e8-8326-990408a2230e.PNG)

If that's not something easily achievable, then don't worry about it. I rarely need to use "using" in that way, and the other commands don't have the same issue.

**Comment by jeffreyschoch** [comment]
@Leopotam Excellent, this works perfectly.  I really appreciate the support.  This fulfills my request completely, let me know if there's anything else you need from me regarding this issue.

Thank you!

**Comment by Leopotam** [comment]
@jeffreyschoch 0.0.58 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@jeffreyschoch if this extension useful for you, can you write review at marketplace, please? :)

**Comment by jeffreyschoch** [comment]
@Leopotam I will be sure to do that.
