### ISSUE TITLE
Broken format for "var a = new Dictionary<string, string> ();"

### ISSUE THREAD

**Issue by skryshi** [Leopotam/vscode-csharpfixformat#5]
## Environment data
C# FixFormat extension version:

0.0.15

## Steps to reproduce

type in this code `var a = new Dictionary<string, string> ();` and run Fix Format command

## Expected  behavior

`var a = new Dictionary<string, string> ();`

## Actual behavior

```      
var a = new Dictionary < string,
string > ();
```

**Comment by Leopotam** [comment]
confirmed. temporary workaround - use full type signature instead of "var" keyword.

**Comment by Leopotam** [comment]
@skryshi can you confirm that issue fixed in 0.0.16?

**Comment by skryshi** [comment]
Fixed, thank you! You are fast )
