### ISSUE TITLE
Inconsistent spacing around casts

### ISSUE THREAD

**Issue by jeffreyschoch** [Leopotam/vscode-csharpfixformat#50]
### C# FixFormat extension version:
v0.0.58

### VsCode version:
v1.19.2

## Steps to reproduce
Apply the following settings to the workspace:
```
"csharpfixformat.style.spaces.beforeParenthesis": false,
"csharpfixformat.style.spaces.afterParenthesis": false,
"csharpfixformat.style.spaces.removeAfterCommandBeforeParenthesis": "if for foreach while switch catch using default",
```
recreate this example class:
```cs
public class Example {
	public void Main() {
		float f = 10f;
		int i = (int) f;                // space added before and after
		bool b1 = i < (int) f;		// space before and after cast
		bool b2 = i >(int) f;		// space before is removed, space after remains
		bool b3 = i >= (int) f;		// space before and after cast
		bool b4 = i >(int)(f * 2f);	// spaces removed before and after
	}
}
```

Apply the autoformatter and observe the spacing around the casts.

## Expected  behavior
Spaces will consistently be added before and/or after parentheses according to the workspace/user settings, in boolean expression context or otherwise.

I'm not sure if this represents a bug in the existing settings, or requires additional settings for user control over this behavior.

## Actual behavior
Spaces will be added/removed in a seemingly inconsistent manner, depending on context.

**Comment by Leopotam** [comment]
@jeffreyschoch so, all spaces between logical operators and cast parentheses should be removed?

**Comment by Leopotam** [comment]
@jeffreyschoch can you uninstall previous version and check this one? 
[csharpfixformat-0.0.59.vsix.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1665373/csharpfixformat-0.0.59.vsix.zip)

**Comment by jeffreyschoch** [comment]
That version appears to apply the formatting correctly. Nice work!

**Comment by Leopotam** [comment]
@jeffreyschoch 0.0.59 released on official marketplace, you can uninstall custom package and install public release. thanks.
