### ISSUE TITLE
Inconsistent spacing around colons when using named optional parameters

### ISSUE THREAD

**Issue by jeffreyschoch** [Leopotam/vscode-csharpfixformat#51]
### C# FixFormat extension version:
v0.0.58

### VsCode version:
v1.19.2

## Steps to reproduce
Apply the following settings to the workspace (my current settings, not sure if relevant here):
```
"csharpfixformat.style.spaces.beforeParenthesis": false,
"csharpfixformat.style.spaces.afterParenthesis": false,
"csharpfixformat.style.spaces.removeAfterCommandBeforeParenthesis": "if for foreach while switch catch using default",
```
recreate this example class:
```cs
public class Example {
	public void Main() {
		optionals(float1: 0, float2: 0);                                   // spaces removed before colon
		optionals(component: new System.Random(), float1 : 0, float2 : 0); // spaces added before colon
		optionals(component: null, float1: 0, float2: 0);                  // spaces removed before colon
	}

	private void optionals(float float1 = 1, float float2 = 1) { }
	private void optionals(System.Random component = null, float float1 = 1, float float2 = 1) { }
}
```

Apply the autoformatter and observe the spacing around the colons.

## Expected  behavior
Spaces will consistently be added before and/or after colons used with named optional parameters according to the workspace/user settings.

I'm not sure if this represents a bug in the existing settings, or requires additional settings for user control over this behavior.

## Actual behavior
Spaces will be added/removed in a seemingly inconsistent manner, depending on context.

## Desired outcome
I'm looking for the colon in this context (named parameter) to never have a space before it, but always have a space after it.

**Comment by Leopotam** [comment]
@jeffreyschoch can remove previous version and try this one?
[csharpfixformat-0.0.59.vsix.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1665705/csharpfixformat-0.0.59.vsix.zip)

**Comment by jeffreyschoch** [comment]
That appears to have fixed the inconsistency.  Thanks again for your time and effort!

**Comment by Leopotam** [comment]
@jeffreyschoch 0.0.59 released on official marketplace, you can uninstall custom package and install public release. thanks.
