### ISSUE TITLE
Option to disable indentation of classes within namespaces

### ISSUE THREAD

**Issue by 41407** [Leopotam/vscode-csharpfixformat#53]
An option to disable indentation of classes within namespaces would be awesome. See below for an example.

For instance, when formatting a file, Visual Studio automatically keeps unindented classes within namespaces unindented while VSCode always indents them. I have been looking for a way to disable automatic indentation of classes within namespaces but haven't found one. 

Otherwise, many thanks for this great extension!

### C# FixFormat extension version:
0.0.59

### VsCode version:
1.19.3

## Steps to reproduce

Let's say we start with an unindented class `MyClass` within namespace `MyNamespace`.

```csharp
namespace MyNamespace {

public class MyClass {
    // ...
```

## Expected  behavior

When formatting a document with the suggested option enabled, `MyClass` would remain unindented.

```csharp
namespace MyNamespace {

public class MyClass {
    // ...
```

When the suggested option is disabled, formatting the document would result in the following:

```csharp
namespace MyNamespace {

    public class MyClass {
        // ...
```

## Actual behavior

When formatting the document, this is what currently happens.

```csharp
namespace MyNamespace {

    public class MyClass {
        //  ...
```

**Comment by Leopotam** [comment]
@41407 there are no any differences between `namespace`, `class`, `enum`, etc. This extension is not proper c# parser / ast scanner, its regexp based solution for plain text. Only one case presents - "new scope" with opening "{" and closing "}" braces. So, no, this issue cant be solved fast and with current implementation, sorry about it. Better to wait for official `omnisharp` extension for proper formatting then. :)
