### ISSUE TITLE
Option to sort Microsoft usings separately (like System)

### ISSUE THREAD

**Issue by AOne-T** [Leopotam/vscode-csharpfixformat#54]
When developing for .NET Core you almost couldn't avoid using Microsoft specific namespaces. I think it should be convenient to sort the separately as System namespaces and place them between System and custom namespaces.

Maybe there should be an option for it.

### C# FixFormat extension version:
v0.0.59

### VsCode version:
1.19.3

## Steps to reproduce
Select usings block -> Right Click -> Format Selection

## Expected  behavior
using System;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.PlatformAbstractions;
using Account;
using AutoMapper;
using Logging;
using Newtonsoft.Json;
using WebDAV;

## Actual behavior
using System;
using System.IO;
using Account;
using AutoMapper;
using Logging;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.PlatformAbstractions;
using Newtonsoft.Json;
using WebDAV;

**Comment by Leopotam** [comment]
@AOne-T
> Select usings block -> Right Click -> Format Selection

Formatting of selection not supported, format style will be applied to whole document. Just for your information. :)

**Comment by Leopotam** [comment]
@AOne-T can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@AOne-T no feedback, closed as fixed. 0.0.60 version released on marketplace.
