### ISSUE TITLE
Allow to configure conditions operators placement

### ISSUE THREAD

**Issue by Oleksandr-Silin** [Leopotam/vscode-csharpfixformat#56]
### C# FixFormat extension version:

0.0.61

### VsCode version:
1.20.0

## Steps to reproduce
 add next code:

```
return user != null 
       &&  user.UserState == UserState.Active 
       &&  user.Password == loginViewModel.Password;
```

## Expected  behavior
 it will leave it or reformat to next stlye:

```
return user != null 
       &&  user.UserState == UserState.Active 
       &&  user.Password == loginViewModel.Password;
```

## Actual behavior (reformats to this style)
```
return user != null &&
       user.UserState == UserState.Active &&
       user.Password == loginViewModel.Password;
```

**Comment by Leopotam** [comment]
@Oleksandr-Silin can you check last state of develop branch? is issue fixed for you?

**Comment by Oleksandr-Silin** [comment]
Amazing! ty it does what i need!

**Comment by Leopotam** [comment]
@Oleksandr-Silin 0.0.62 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@Oleksandr-Silin if this extension useful for you, can you write review at marketplace, please? :)
