### ISSUE TITLE
Spaces before parenthesis in commands but not in functions

### ISSUE THREAD

**Issue by jlreymendez** [Leopotam/vscode-csharpfixformat#57]
### C# FixFormat extension version:
0.0.64

### VsCode version:
1.20.1

## Steps to reproduce
Write code like:

```
public bool CoolFunction(int p1) {
    if (p1 < 0) { 
      return false;
    }

    for (var i = 0; i < p1; i++) {
       DoStuff(i, p1);
    }
}
```

## Expected  behavior

So basically I like having spaces before parenthesis in commands but not before function declarations or calls. I notice there is a "style.spaces.removeAfterCommandBeforeParenthesis" which would allow me to do the opposite. 

So I propose either having a "style.spaces.addAfterCommandBeforeParenthesis" or if you can somehow work it out "style.spaces.beforeParenthesisInFunctions" (or somehing like it)

## Actual behavior

As far as I could deduce from the current options it isn't possible to have the desired behavior, although I might have missed something.

**Comment by Leopotam** [comment]
@jlreymendez did you tried `style.spaces.beforeParenthesis=false` and `style.spaces.addAfterCommandBeforeParenthesis="keyword1 keyword2"` with all commands that you wanted to see splitted with space?

**Comment by Leopotam** [comment]
@jlreymendez what about `style.spaces.beforeParenthesis=false`?

**Comment by jlreymendez** [comment]
@Leopotam I'm sorry. I was pretty sure I had tested that, but maybe the name led me to believe that it would remove the spaces after statements (if, for, etc.). Thanks for your quick reply!

**Comment by Leopotam** [comment]
@jlreymendez if this extension useful for you, can you write review at marketplace, please? :)
