### ISSUE TITLE
Is there a way to use C# Fix Format on the command line?

### ISSUE THREAD

**Issue by ataias** [Leopotam/vscode-csharpfixformat#59]
I was wondering if there is a command line to use C# Fix Format or any other tool that you guys would recommend. For me, it would be nice to have a command line util so that it is easier to integrate it with git hooks.

**Comment by Leopotam** [comment]
This extension designed to work inside of `vscode` infrastructure - it cant be run outside of `vscode` as standalone app. As solution, you can use `"editor.formatOnSave": true` for autoformatting on any file save.
