### ISSUE TITLE
Adds a space before paranthesis for generic methods

### ISSUE THREAD

**Issue by umutozel** [Leopotam/vscode-csharpfixformat#6]
### C# FixFormat extension version:
0.0.18

### VsCode version:
1.10.2

## Steps to reproduce
Any generic method:
public TOut Map<TIn, TOut> (TIn inObj)

## Expected  behavior
Should not add space after > (generic definition close) when csharpfixformat.style.spaces.beforeParenthesis is false

## Actual behavior
Adds a space before paranthesis

**Comment by Leopotam** [comment]
@umutozel can you check 0.0.19 release? is issue fixed?

**Comment by umutozel** [comment]
I've just updated to 0.0.19 and it works. Thank you.
