### ISSUE TITLE
Produce API

### ISSUE THREAD

**Issue by DifficultNick** [Leopotam/vscode-csharpfixformat#60]
I'll be very thankful if you will produce API for `class FormatProvider` cause I want to use it in my extension with special language.

As I understand, this can be done by adding just one string:
`return {FormatProvider};`
at the end of your activate function.

Thanks!

**Comment by Leopotam** [comment]
Not sure that it will be enough for api, better to create additional command and use it through vscode api:
```
interface IExternalFormatter extends vs.DocumentRangeFormattingEditProvider, vs.OnTypeFormattingEditProvider { }

const newFormatter = await vs.commands.executeCommand<IExternalFormatter>('csharpfixformat.API_getFormatter');
vs.window.showInformationMessage(`formatter instance not null: {${newFormatter !== null}}`);
```

Can you check this case with version from "develop" branch?

**Comment by DifficultNick** [comment]
![image](https://user-images.githubusercontent.com/18598163/37848906-cbdb3768-2ee6-11e8-94e2-26e6ac823e60.png)

But how should i use it?

More information about my need: my language has embedded C#, so I need to format some parts of string as C# (and your ext do this very nice!). As soon as I've got some FormatProvider, I can only format selected text or the whole document (am I right?).

But if your activate function will return `formatting` (I was wrong about FormatProvider, sorry) than I'll be able to call its `process` function.
Or even better, something like this:
```TypeScript
var FormatCS = function (text: string)
{
    return formatting.process(text, getFormatOptions());
}
```
and than `activate` function should `return { FormatCS  }`.

Maybe this way is ugly, but I see it more comfortable to use :)

Thank you for considering this issue!

**Comment by Leopotam** [comment]
And how you will provide formatting options then? Why you think that `activate` function will work for you? You cant control it, its part of extension registration and you cant call it directly (vscode does it once and in valid place), same for `deactivate`. You can register new instance of formatter as [standard formatter for your language (with proper lang-id / extension)](https://github.com/Leopotam/vscode-csharpfixformat/blob/master/src/extension.ts#L103).

**Comment by DifficultNick** [comment]
I will just activate your extension (if it's not active already) and than get function in this way:
```TypeScript
var FormatCS = vs.extensions.getExtension('Leopotam.csharpfixformat').exports["FormatCS"];
```
as written in [extensions namespace documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_extensions)
And your extension will take all its options itself.
I've tested it with "develop" branch code, it seems everything works well.

**Comment by Leopotam** [comment]
```
const fixformat = vs.extensions.getExtension('Leopotam.csharpfixformat');
const api = fixformat.exports;
const source = 'class          A{\npublic int N; }';
const options = api.getOptions();
const formatted = await api.process(source, options);
```

@DifficultNick, its good for you?

**Comment by DifficultNick** [comment]
Yeah, this is just what I need!

**Comment by Leopotam** [comment]
@DifficultNick check then "develop" branch, please.

**Comment by DifficultNick** [comment]
It works great!

**Comment by Leopotam** [comment]
@DifficultNick 0.0.65 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@DifficultNick if this extension useful for you, can you write review at marketplace, please? :)
