### ISSUE TITLE
Please add option to turn off Egyptian style brackets

### ISSUE THREAD

**Issue by rraallvv** [Leopotam/vscode-csharpfixformat#61]
Visual Studio for Mac doesn't have support for Egyptian style brackets, so it'd be very welcome to have a way to turn it off and have brackets formatted like VS for Mac does. Otherwise one might end up with a mixture of different brackets formatting styles overtime.

Keep up the good work!

**Comment by Leopotam** [comment]
@rraallvv did you checked `README` description of options?

> csharpfixformat.style.braces.onSameLine: Should open braces be kept on expression line (K&R style) or on new line. True by default.

**Comment by rraallvv** [comment]
@Leopotam it did the trick, thanks.
