### ISSUE TITLE
New line at the end of file

### ISSUE THREAD

**Issue by AmirSavand** [Leopotam/vscode-csharpfixformat#62]
When I format the script, the line at the end of file gets removed.

Is there an option to add a new line at the end of file?

**Comment by Leopotam** [comment]
There are no special behaviour for new lines - any whitespace characters from start and end of source code will be force removed in current implementation.

**Comment by Leopotam** [comment]
@AmirSavand can you check last state of develop branch? is issue fixed for you?    

> "style.newline.atEnd" option was added.

**Comment by AmirSavand** [comment]
I don't know how to do so.

**Comment by Leopotam** [comment]
@AmirSavand check this:
[csharpfixformat-0.0.66.vsix.zip](https://github.com/Leopotam/vscode-csharpfixformat/files/1865507/csharpfixformat-0.0.66.vsix.zip)

**Comment by Leopotam** [comment]
@AmirSavand no feedback, closed as fixed. 0.0.66 version released on marketplace.
