### ISSUE TITLE
Same line brace style should be false by default

### ISSUE THREAD

**Issue by valtism** [Leopotam/vscode-csharpfixformat#63]
For better or for worse, the most widely adopted brace style convention in C# is Allman style. Because of that, I think that this extension should use that style as default instead of K&R style.

**Comment by Leopotam** [comment]
Its my default code style and you have ability to set your custom style, so, nothing will be changed. If you dont like default behaviour, you can wait when microsoft omnisharp extension will support it.

**Comment by Leopotam** [comment]
@valtism duplicate: #25
