### ISSUE TITLE
Formatting error on Digit Separator in Numeric Literal - C# 7  

### ISSUE THREAD

**Issue by gersonmartins** [Leopotam/vscode-csharpfixformat#65]
### C# FixFormat extension version:

0.0.66

### VsCode version:

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64 - Linux

## Steps to reproduce

Write a numeric literal variable or property with underscore as a digit separator. This feature was introduced on C# 7 (Visual Studio 2017)

```csharp
int timeout = 4_000;
int NewTimeout { get; set; } = 100_000_000;
```
Run FixFormat (`CTRL+SHIFT+i`)

## Expected  behavior

No changes, once the code is formatted.

```csharp
int timeout = 4_000;
int NewTimeout { get; set; } = 100_000_000;
```

## Actual behavior

A `space` is placed between first number and underscore.

```csharp
int timeout = 4 _000;
int NewTimeout { get; set; } = 100 _000_000;
```

**Comment by Leopotam** [comment]
@gersonmartins can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@gersonmartins no feedback, closed as fixed. 0.0.67 version released on marketplace.
