### ISSUE TITLE
Nesting an enum inside class adds extra indentation to following properties

### ISSUE THREAD

**Issue by gpoole** [Leopotam/vscode-csharpfixformat#66]
### C# FixFormat extension version:
0.0.66

### VsCode version:
1.21.1

## Steps to reproduce

Adding a nested enum to any class seems to cause all the following properties to be indented up to the first method. For example in this class:

```cs
public class PlayerState : MonoBehaviour {

	public enum Mode {
		Starting,
		Racing,
		Finished,
	};

	public Player player;

	public int lap = 1;

	// snip...

	void Start() {
		// snip...
	}

	void Update() {
		// snip...
	}
}
```

## Expected  behavior

```cs
public class PlayerState : MonoBehaviour {

	public enum Mode {
		Starting,
		Racing,
		Finished,
	};

	public Player player;

	public int lap = 1;

	// snip...

	void Start() {
		// snip...
	}

	void Update() {
		// snip...
	}
}
```

## Actual behavior

```cs
public class PlayerState : MonoBehaviour {

	public enum Mode {
		Starting,
		Racing,
		Finished,
		};

		public Player player;

		public int lap = 1;

		// snip...

		void Start() {
		// snip...
	}

	void Update() {
		// snip...
	}
}
```

**Comment by gpoole** [comment]
I've also noticed a different version of the problem if I move the enum declaration above the class:

```cs
public enum Mode {
	Starting,
	Racing,
	Finished,
};

public class PlayerState : MonoBehaviour {

	public Player player;

	public int lap = 1;

	// snip...

	void Start() {
	// the body of the Start function is only indented to here
	// snip...
	}

	void Update() {
		// snip...
	}
}
```

**Comment by Leopotam** [comment]
@gpoole just remove `;` after enum - it will fix issue:
```
public enum Mode {
    Starting,
    Racing,
    Finished,
}
```

**Comment by UnsolvedCypher** [comment]
If this is the case, could you add functionality to automatically remove the semicolon so that the formatting can happen correctly? It seems unintuitive that otherwise the formatting gets messed up for seemingly no reason.

**Comment by Leopotam** [comment]
@UnsolvedCypher can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@UnsolvedCypher no feedback, closed as fixed. 0.0.82 version released on marketplace.
