### ISSUE TITLE
Feature request: an option for not indenting "case"

### ISSUE THREAD

**Issue by wdscxsj** [Leopotam/vscode-csharpfixformat#68]
Many code formatters for C-family languages provide an option to not indent "case" statements. I guess a similar option like `csharpfixformat.style.indent.caseIgnored` will benefit C# code, too. Thanks a lot for your consideration.

**Comment by Leopotam** [comment]
@wdscxsj can you check last state of develop branch? is issue fixed for you?

> * "style.indent.switchCaseIgnored" option was added.

**Comment by wdscxsj** [comment]
It works wonderfully. Thank you!

**Comment by Leopotam** [comment]
@wdscxsj 0.0.68 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@wdscxsj if this extension useful for you, can you write review at marketplace, please? :)

**Comment by wdscxsj** [comment]
@Leopotam So glad to. Just posted the review. :)

**Comment by Leopotam** [comment]
@wdscxsj thanks!

**Comment by wdscxsj** [comment]
@Leopotam Another glitch I've noticed (which may not warrant its own issue report) is formatting `enum`s with a trailing `;`. For example:

```
class Foo {
	enum One { A };
	enum Two { B };
}
```

will be formatted to:

```
class Foo {
    enum One { A };
 enum Two { B };
}
```

As my C# is too rusty, I take this as a reminder that the trailing `;` is unnecessary (though harmless). But someone may think it's the formatter's fault...

**Comment by Leopotam** [comment]
#66

**Comment by wdscxsj** [comment]
Thanks! A reminder it is. 😄
