### ISSUE TITLE
Broken format for generic variable

### ISSUE THREAD

**Issue by umutozel** [Leopotam/vscode-csharpfixformat#7]
### C# FixFormat extension version:
0.0.19

### VsCode version:
1.10.2

## Steps to reproduce
Create a generic variable with options:
    "csharpfixformat.style.spaces.beforeIndexerBracket": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.beforeBracket": false,
    "csharpfixformat.style.spaces.afterBracket": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,

adds a space before ',' and '>' (only last one).

## Expected  behavior
ConcurrentDictionary<Tuple<Type, Type>, MapDefinition> _mapDefinitions

## Actual behavior
ConcurrentDictionary<Tuple<Type, Type> , MapDefinition > _mapDefinitions

**Comment by Leopotam** [comment]
@umutozel can you check develop branch? installation instructions at readme.

**Comment by umutozel** [comment]
It works now thanks, you are really fast 👍

**Comment by umutozel** [comment]
I closed the issue, should I have waited for the package release?

**Comment by Leopotam** [comment]
0.0.20 published, thanks.
