### ISSUE TITLE
Feature Request - Conditional Else on Separate Line

### ISSUE THREAD

**Issue by zcr1** [Leopotam/vscode-csharpfixformat#70]
It would be useful to have ability to place conditionals on a separate line of the closing bracket i.e.
```
if (foo){

}
else{

}
```

Apologies if the setting is already in and I missed it. Thanks for the awesome extension!

**Comment by Leopotam** [comment]
@zcr1 what about next behaviour?
```
if (foo)
{
}
else
{
}
```

**Comment by zcr1** [comment]
I prefer `Should open braces be kept on expression line (K&R style) or on new line` to be true so I guess i use a combination of both? It's not a big deal either way as I can deal with it :)

**Comment by Leopotam** [comment]
@zcr1 try-catch will be formatted with same rule as if-esle, its ok?

**Comment by Leopotam** [comment]
@zcr1 can you check last state of develop branch? is issue fixed for you?
> "style.newline.elseCatch" option was added.

**Comment by zcr1** [comment]
Tested it out and it works on my end. Thanks a lot, much appreciated!

**Comment by Leopotam** [comment]
@zcr1 0.0.69 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@zcr1 if this extension useful for you, can you write review at marketplace, please? :)
