### ISSUE TITLE
Request: Can "csharpfixformat.sort.usings.order" sort by alphabetical order, alphanumeric order, and by length of string names?

### ISSUE THREAD

**Issue by tommai78101** [Leopotam/vscode-csharpfixformat#71]
### VsCode version: Stable 1.23

This is a feature request to add more sorting algorithms for `using` preprocessor directives. Right now, there is only 1 sort order given, `System`. I would like to see more options.

- Alphabetical Order - Based on entire namespace string's alphabetical order from left to right.

It's only sorted based on ASCII characters.

- Alphanumeric Order - Same as above, but includes Unicodes and symbols, based on the specs given below:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers

- Length - Based on the length of the entire namespace string that's occupying 1 line.

Example for `Length`:

Here's a given namespaces list.

```Csharp
using System.Globalization;
using System.Linq;
using System.IO;
using System.Collections;
```

If using `Length`, it would sort it from shortest length of string to longest length of string in descending order, regardless of alphabetical order:

```csharp
using System.IO;
using System.Linq;
using System.Collections;
using System.Globalization;
```

**Comment by Leopotam** [comment]
> there is only 1 sort order given, System

You can check `sort.usings.order` option - you can set any order for well-known namespaces (even per project).

> but includes Unicodes and symbols, based on the specs 

Sorry, its not 100% C# specs compatible extension, even on features. For full C# specs you can wait for official omnisharp extension. As for me, using unicode (or any non-latin chars) in identifier names - very bad idea.

> Based on the length of the entire namespace

It will conflict with `sort.usings.order` option.

Main idea of this option - try to make `usings` order closer to possible formatting in `VisualStudio`.

**Comment by tommai78101** [comment]
1. Oh, so that's how you use `sort.usings.order`. I believed I would need to specify what namespaces take priority when sorting them, and list them in order from left to right. 

    If that's the case, then that's one thing I got right about, since I was confused about the option when I was checking the `readme.md`.

2. OK, I can wait for omnisharp for the formatting. It's just, I thought that the C# specs are followed strictly, even if there are Unicodes and symbols in the identifiers of the namespaces.

3. Same as (1.), I'll play around with the `sort.usings.order` based on the new information. And yeah, hopefully it can automatically order closer to the current formatting in Visual Studio.

**Comment by tommai78101** [comment]
> Well, its how VisualStudio usings sorter works - there is special option for keep System.xxx lines at start of block.

I never knew this.

**Comment by Leopotam** [comment]
https://stackoverflow.com/questions/14829853/vs2012-sort-usings-doesnt-move-system-usings-first

**Comment by Leopotam** [comment]
@tommai78101 another one article with details: https://blogs.msdn.microsoft.com/zainnab/2010/06/29/organize-usings-c-only/

**Comment by tommai78101** [comment]
@Leopotam Thanks again.
