### ISSUE TITLE
Feature Request: Indent code in preprocessor block

### ISSUE THREAD

**Issue by TheHacky** [Leopotam/vscode-csharpfixformat#72]
Hi,

I downloaded your extension some minutes ago and it is so much better than the classical omnisharp formatting. So, nice work have you done.

I have one question. Will it be possible to add an option for indenting a code block between a preprocessor block.

## Expected  behavior
```csharp
public void Quit ()
{
    #if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
    #else // UNITY_EDITOR
        Application.Quit ();
    #endif // UNITY_EDITOR
 }
```

## Actual behavior
```csharp
public void Quit ()
{
    #if UNITY_EDITOR
    UnityEditor.EditorApplication.isPlaying = false;
    #else // UNITY_EDITOR
    Application.Quit ();
    #endif // UNITY_EDITOR
 }
```

Thanks.

Best regards,
David

**Comment by Leopotam** [comment]
Indentation should works in same manner with or without preprocessor defines - its standard behaviour in all editors. You can change preprocessor defines indentation (not code blocks inside) with  `csharpfixformat.style.indent.preprocessorIgnored` option.
