### ISSUE TITLE
Feature Request: Same Indentation for multiline parameters

### ISSUE THREAD

**Issue by TheHacky** [Leopotam/vscode-csharpfixformat#73]
Hi,

what's about indentation for multiline parameters?

## Expected  behavior
```csharp
Class c = new Class(param1,
                    param2,
                    param2);
```

## Actual behavior
```csharp
Class c = new Class(param1,
    param2,
    param2);
```

Thanks.

Best regards,
David

**Comment by Leopotam** [comment]
There are no real AST parser of C# specs. It means - formatter dont know where are first parameter, just check possible end of expression based on braces / parantesis balance + simple indentation for each new level of nested expressions. Sorry, but I think, this extension will not help you in this case.

**Comment by TheHacky** [comment]
Is okay. Your extension is brilliant and I have write you a review on marketplace. Actually, the best indentation extension I found.
