### ISSUE TITLE
Destroys formatting of manual horizontal positions

### ISSUE THREAD

**Issue by sirgru** [Leopotam/vscode-csharpfixformat#78]
After formatting, all the manual horizontal positions are destroyed.
For example, if variables are "vertically aligned", this will be reduced to a space. This happens even when tabs are not converted to spaces.

**Comment by Leopotam** [comment]
Its default behaviour of this extension. If you want to keep manual formatting - better  to uninstall this extension and use omnisharp extension only, looks like it will work as you want.
