### ISSUE TITLE
"Format Document" doesn't work if another document formatter exists

### ISSUE THREAD

**Issue by Falthazar** [Leopotam/vscode-csharpfixformat#79]
### VsCode version: 1.24.1

If another extension, in this case CS-Script, has a _document_ formatter, C# Fixformat will not run on the document when you run "Format Document".

The CS-Script formatter is disabled, but I think that because it is still implementing "vscode.DocumentFormattingEditProvider" it overwrites FixFormats formatter. FixFormat doesn't implement the document formatter, just the range and type formatter.

If you select all and run "Format Selection" FixFormat will work correctly.

**Comment by Leopotam** [comment]
@Falthazar can you try to uninstall `CS-Script` extension and check again?

**Comment by Falthazar** [comment]
Sorry! Forgot to put that in the initial post. Disabling the CS-Script extension makes fix format work normally.

**Comment by Leopotam** [comment]
@Falthazar then its how format extensions works inside vscode. Solution - making request to author of `CS-Script` for optional disabling format feature through user settings, like i did here for omnisharp: https://github.com/OmniSharp/omnisharp-vscode/issues/1711
