### ISSUE TITLE
The "cleaner" is erroneously formatting the literal string

### ISSUE THREAD

**Issue by bernardbr** [Leopotam/vscode-csharpfixformat#8]
Hi!

I catched a problem when we have literal strings in source code.

Thanks!

### C# FixFormat extension version:
0.0.20

### VsCode version:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

## Steps to reproduce

Write a const like this:
```csharp
        private const string SCRIPT_UPDATE = @"
        UPDATE
            MyTable
        SET
            {0}
        WHERE
            (Id= @Id)";
```

Do the clean "Ctrl + Alt + I"

## Expected  behavior

The literal string must be intalterated

## Actual behavior

The string will be:

```csharp
        private const string SCRIPT_UPDATE = @"
        UPDATE
        MyTable
        SET
        { 0 }
        WHERE
        (Id= @Id)";
```

And the ```format``` index and has a new space before ```{```and then ```}```

**Comment by Leopotam** [comment]
@bernardbr for temporary fix you can use ignore-wrapper:
```
/* fixformat ignore:start */
        private const string SCRIPT_UPDATE = @"
        UPDATE
            MyTable
        SET
            {0}
        WHERE
            (Id= @Id)";
/* fixformat ignore:end */
```

**Comment by bernardbr** [comment]
Thanks!

**Comment by Leopotam** [comment]
@bernardbr, can you check develop branch? is issue fixed for you?

**Comment by bernardbr** [comment]
Hello @Leopotam I did this:

- Uninstall the public version
- Install node.js.
- Run "npm install" from project folder.
- Run "npm run package" from project folder.
- Install brand new packed *.vsix bundle through vscode plugins menu option "Install from VSIX".

And try again. But the behavior is the same of the public version...

**Comment by Leopotam** [comment]
@bernardbr dont forget - "develop" branch, not "master" (default).

**Comment by bernardbr** [comment]
@Leopotam Sorry, my fault. I forgot -b param...

It's perfect! Works fine! Thank you very much!

**Comment by Leopotam** [comment]
@bernardbr, if it works for you, can you write review at marketplace, please? :)

**Comment by bernardbr** [comment]
Of course!

**Comment by Leopotam** [comment]
@bernardbr, 0.0.21 released on official marketplace, you can uninstall custom package and install public release. thanks.
