### ISSUE TITLE
Space between parenthesis and &

### ISSUE THREAD

**Issue by clragon** [Leopotam/vscode-csharpfixformat#80]
### C# FixFormat extension version:
0.0.71

### VsCode version:
1.25.0

## Steps to reproduce
- New `.cs` file
- following user settings:
```
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,
```

- if statement like this: 
```
if ( ( i > 0 ) && ( 0 <= i ) && ( i >= 0 ) ) { }
```
- format (ALT+SHIFT+F)

## Expected  behavior
I would appreciate if there would be a setting or default behavior that leads to an if statement like this:
```
if ((i > 0) && (0 <= i) && (i >= 0)) { } 
```

## Actual behavior
But the actual result looks like this:
```
if ((i > 0)&& (0 <= i)&& (i >= 0)) { } 
```

-- regards.

**Comment by Leopotam** [comment]
@clragon can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@clragon no feedback, closed as fixed. 0.0.72 version released on marketplace.

**Comment by clragon** [comment]
@Leopotam Sorry, I didn't have time. It's fixed indeed, thanks alot!
