### ISSUE TITLE
Sometimes text parameters will be split into multiple lines

### ISSUE THREAD

**Issue by TheHacky** [Leopotam/vscode-csharpfixformat#81]
### C# FixFormat extension version:
0.0.71

### VsCode version:
1.25.0

## Steps to reproduce
```
[MenuItem("Tools/Open Cmd (ADB)")]
    public void TestMethod() {}
```

or

```
startInfo.WorkingDirectory = @EditorPrefs.GetString("AndroidSdkRoot") + "/platform-tools";
```

## Expected  behavior
```
[MenuItem("Tools/Build for Android (Development)")]
    public void TestMethod() {}
```

or

```
startInfo.WorkingDirectory = @EditorPrefs.GetString("AndroidSdkRoot") + "/platform-tools";
```

## Actual behavior
```
[MenuItem("
			Tools / Build
			for Android(Development)
			")]
    public void TestMethod() {}
```

or

```
startInfo.WorkingDirectory = @EditorPrefs.GetString("
			AndroidSdkRoot ") + " / platform - tools ";
```

I can also send you an example file if needed, but I think it happens after the Verbatimstring for all following strings.

**Comment by Leopotam** [comment]
@TheHacky can you check last state of develop branch? is issue fixed for you?

**Comment by TheHacky** [comment]
@Leopotam It seems to work. Nice! You are awesome! :)

**Comment by Leopotam** [comment]
@TheHacky 0.0.72 released on official marketplace, you can uninstall custom package and install public release. thanks.
