### ISSUE TITLE
csharpfixformat.style.spaces.afterBracket not applying to parameter attribute tag

### ISSUE THREAD

**Issue by andrewb273** [Leopotam/vscode-csharpfixformat#82]
### C# FixFormat extension version:
0.0.72

### VsCode version:
1.25.1

## Steps to reproduce
1. Set `"csharpfixformat.style.spaces.afterBracket": false`
2. Add a function with an attribute tag on a parameter, like so

    public IActionResult DoStuff([FromQuery] int param)
    {
    	//...
    }
3. Auto-format

## Expected  behavior
Space after `]` is removed

## Actual behavior
Space is retained, and if space isn't present, it is added

OR

Space / lack of space isn't modified

Note that the default VS 2017 behaviour is to not touch spacing between parameters. Looking around online, I'm seeing a mixture of with space and without space. It'd be helpful to allow those who prefer no space to use this extension.

**Comment by Leopotam** [comment]
@andrewb273 there are no real AST parser of C# specs. It means - formatter dont know where are attributes and they can be applied to parameters, just check possible end of expression (java / javascript) based on braces / parantesis balance + simple indentation for each new level of nested expressions. Sorry, but I think, this extension will not help you in this case, better to wait for official omnisharp extension for proper formatting then.

**Comment by andrewb273** [comment]
Ah ok, makes sense and all good. It's not a bad handling in any case, so we can probably cope. Thanks for your work & the lightning quick response - rare to find such a heavily used repo with no outstanding issues!
