### ISSUE TITLE
switch case format problem

### ISSUE THREAD

**Issue by sirius0xff** [Leopotam/vscode-csharpfixformat#83]
### C# FixFormat extension version:
0.0.72

### VsCode version:
1.25.1

## Steps to reproduce
format the following code:

```        
int abc = 2;
switch (abc) {
    case 1:{
        int k = 1;
        break;
    }
    case 2:
        goto case 1;
    case 3:
        goto default;
    default:
        goto case 1;
}
```

## Expected  behavior
```        
int abc = 2;
switch (abc) {
    case 1:{
        // brace should not add indent here
        int k = 1;
        break;
    }
    case 2:
        goto case 1; // goto case x should be kept in one line
    case 3:
        goto default; // goto default should be kept in one line
    default:
        goto case 1;
}
```

## Actual behavior

Two problems

```        
int abc = 2;
switch (abc) {
    case 1:
        {
            // brace add indent 
            int k = 1;
            break;
        }
    case 2:
        goto
    case 1;// misleading new line
    case 3:
        goto
    default;// misleading new line
    default:
        goto
    case 1;// misleading new line
}
```

Thank you

**Comment by Leopotam** [comment]
@sirius0xff there are 2 issues.
1. braces at `case 1`: they are optional and can / should be removed - it will fix issue with invalid indentation.

2. "goto" operator. i'm totally disagree that this operator should even exists in c#, but... can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@sirius0xff no feedback, closed as fixed. 0.0.73 version released on marketplace.

**Comment by sirius0xff** [comment]
Sorry for late feedback.
About the brace, they actually define scopes which allow different variables of same name to be defined under difference case labels.

**Comment by Leopotam** [comment]
@sirius0xff sorry, but its not real C# AST parser / lexer and there are no support for nested braces at top level inside case. If you need this behaviour - better to uninstall this extension and wait for official support from Microsoft at their [omnisharp-vscode repo](
https://github.com/OmniSharp/omnisharp-vscode/issues).

**Comment by sirius0xff** [comment]
No need to feel offended, just some suggestion.
An the update works, thank you very much.
