### ISSUE TITLE
Nesting more than two generics causes too many spaces

### ISSUE THREAD

**Issue by wardie93** [Leopotam/vscode-csharpfixformat#84]
### C# FixFormat extension version:

0.0.73

### VsCode version:

1.26.0

## Steps to reproduce

Use the following class, and format the file

```
public class Test
{
    public Task<Expression<Func<Test>>> Method()
    {

    }
}
```

## Expected  behavior

There should not be any spaces between the second and third `>`

## Actual behavior

A space is added between the second and third `>`.

I hope this is enough information, if you need any more let me know.

**Comment by Leopotam** [comment]
@wardie93 can you check last state of develop branch? is issue fixed for you?

**Comment by wardie93** [comment]
Thanks Leopotam for the quick turnaround. That does fix the issue I was having!

Whilst I have you, I'm not sure if this intended or not, or I just have things mis-configured or something. But I am getting a strange formatting for getters/setters. If there is a setting that gives me the expected outcome or something that would be great 😄 

Expected:
```
public class Test
{
     public string Property { get; set; }
}
```

Actual
```
public class Test
{
    public Property
    {
        get;
        set;
    }
}
```

**Comment by Leopotam** [comment]
> or I just have things mis-configured or something.

check `csharpfixformat.style.braces.allowInlines` settings, it should be `true` for one-liners.

**Comment by Leopotam** [comment]
@wardie93 0.0.74 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@wardie93 if this extension useful for you, can you write review at marketplace, please? :)

**Comment by wardie93** [comment]
Ah, brilliant, thanks.

I set that to `false` for some reason. Can't remember why though to be honest.

Nevermind, I'll continue with it as true. Thanks for all your assistance!

Also, added a review for you!
