### ISSUE TITLE
Incorrect formatting after lambda => operator

### ISSUE THREAD

**Issue by sundriftproductions** [Leopotam/vscode-csharpfixformat#87]
## Environment data
I have my C# FixFormat settings set up like this:

    "csharpfixformat.style.braces.onSameLine": false, 
    "csharpfixformat.style.spaces.beforeParenthesis": false,  
    "csharpfixformat.style.spaces.afterBracket": false,
    "csharpfixformat.style.spaces.afterParenthesis": false,
    "csharpfixformat.style.spaces.beforeBracket": false,

### C# FixFormat extension version:
0.0.75

### VsCode version:
1.28.0

## Steps to reproduce
Create a line of code with the `=>` lambda operator, followed by an open parenthesis. When saving the file, C# FixFormat will remove the space before the parenthesis -- which is usually what's desired in C# -- except in the case of the `=>` lambda operator.

## Expected  behavior
            List<string> supportedLanguages = languageDoc.Languages.Children().Select(c => ((Newtonsoft.Json.Linq.JProperty)c).Name).ToList();

Notice the space between `>` and `(`.

## Actual behavior

            List<string> supportedLanguages = languageDoc.Languages.Children().Select(c =>((Newtonsoft.Json.Linq.JProperty)c).Name).ToList();

Notice no space between `>` and `(`.

**Comment by Leopotam** [comment]
@sundriftproductions can you check last state of develop branch? is issue fixed for you?

**Comment by sundriftproductions** [comment]
Yes, it's fixed in the develop branch. Thanks!

**Comment by Leopotam** [comment]
@sundriftproductions 0.0.76 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Comment by Leopotam** [comment]
@sundriftproductions if this extension useful for you, can you write review at marketplace, please? :)
