### ISSUE TITLE
incorrect format for variable declaration  inside another one using new operator 

### ISSUE THREAD

**Issue by samousavih** [Leopotam/vscode-csharpfixformat#88]
### C# FixFormat extension version:
0.0.75

### VsCode version:
1.27.2

## Steps to reproduce
When using a new operator to initialise an object inside another one this happens 
```
 new SomeType() {
                new AnotherType() {
                Property1 = 1,
                Property2 = 2,
                Property3 = new MoreType() {
                Property1 = 1,
                }
                },
```

## Expected  behavior

But is should be like : 
```
new SomeType() {
                new AnotherType() {
                      Property1 = 1,
                      Property2 = 2,
                      Property3 = new MoreType() {
                                            Property1 = 1,
                                            }
                },
```

**Comment by Leopotam** [comment]
@samousavih check `Known issues` section at readme. There are no real AST parser of C# specs. It means - formatter dont know anything about recursive initialization, just check possible end of expression based on braces / parantesis balance + simple indentation for each new level of nested expressions. This extension will not help you, better to wait full specs formatting from [official microsoft c# extension](https://github.com/OmniSharp/omnisharp-vscode).
