### ISSUE TITLE
Incorrect formatting within if statement

### ISSUE THREAD

**Issue by sundriftproductions** [Leopotam/vscode-csharpfixformat#89]
## Environment data
I have my C# FixFormat settings set up like this:

     "csharpfixformat.style.braces.onSameLine": false, 
     "csharpfixformat.style.spaces.beforeParenthesis": false,  
     "csharpfixformat.style.spaces.afterBracket": false,
     "csharpfixformat.style.spaces.afterParenthesis": false,
     "csharpfixformat.style.spaces.beforeBracket": false,

### C# FixFormat extension version:
0.0.76

### VsCode version:
1.28.0

## Steps to reproduce
Set up an `if` statement, then put a multiline `if` statement inside of it (where the the `if` statement is broken up into multiple `||` conditions and each condition is on a separate line). The multi-line `if` statement will not keep the correct indentation formatting beyond the first line that has the `if`.

Also, if you set up an object within an `if` statement where you are defining the object's parameters on multiple lines within braces, the indentation of the object will be incorrect.

## Expected  behavior
	public static Country Test()
	{
	    COUNTRY c = _sqlContext.Countries.Where(x => x.ISO_COUNTRY_CODE == countryCode).FirstOrDefault();
	    if (c != null)
	    {
		if (c.NAME != null ||
		    c.ISO_3166_2_CHAR != null ||
		    c.ISO_3166_3_CHAR != null)
		{
		    return new Country()
		    {
		        Name = c.NAME,
		        ISO2 = c.ISO_3166_2_CHAR,
		        ISO3 = c.ISO_3166_3_CHAR
		    };
		}
	    }

	    return null;
	}

## Actual behavior
	public static Country Test()
	{
	    COUNTRY c = _sqlContext.Countries.Where(x => x.ISO_COUNTRY_CODE == countryCode).FirstOrDefault();
	    if (c != null)
	    {
		if (c.NAME != null ||
		c.ISO_3166_2_CHAR != null ||
		c.ISO_3166_3_CHAR != null)
		{
		return new Country()
		{
		Name = c.NAME,
		ISO2 = c.ISO_3166_2_CHAR,
		ISO3 = c.ISO_3166_3_CHAR
		    };
		}
	    }

	    return null;
	}

**Comment by Leopotam** [comment]
@sundriftproductions check [README](
https://github.com/Leopotam/vscode-csharpfixformat#multiline-initialization-for-new-instance-as-parameter-for-method-will-not-be-formatted-correctly), its known issue (just put declaration to new variable and return it) and cant be fixed due there are no real AST parser of current C# specs. It means - formatter dont know all C# features and its very complex task to do this for one-man team. Better to wait for official formatter as part of [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode) extension by Microsoft.
