### ISSUE TITLE
Feature Request: Allow Items in List/Array to be on same line

### ISSUE THREAD

**Issue by djbreen7** [Leopotam/vscode-csharpfixformat#92]
### C# FixFormat extension version:
0.0.78

### VsCode version:
1.30.2

## Steps to reproduce
Format code

## Expected  behavior
```
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };
```

## Actual behavior
```
        private static string[] Summaries = new []
        {
            "Freezing",
            "Bracing",
            "Chilly",
            "Cool",
            "Mild",
            "Warm",
            "Balmy",
            "Hot",
            "Sweltering",
            "Scorching"
        };
```

**Comment by Leopotam** [comment]
@djbreen7 you can put it on one line with`"csharpfixformat.style.braces.onSameLine": true`:
```cs
private static string[] Summaries = new [] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };
```
Another way to keep custom format - wrap it with special flag in comment:
```cs
/* fixformat ignore:start */
var test    =        i().  willNotBeFormatted     []   ;
/* fixformat ignore:end */
```

Otherwise (from readme):
> If you need full format support of last C# version - better to write issue about proper formatting at [Omnisharp extension repo](https://github.com/OmniSharp/omnisharp-vscode/issues).

**Comment by Leopotam** [comment]
@djbreen7 my mistake, sorry, `"csharpfixformat.style.braces.allowInlines": true`, not `"csharpfixformat.style.braces.onSameLine": true`, first comment updated.

**Comment by djbreen7** [comment]
Thanks @Leopotam
