### ISSUE TITLE
There is no document about how to sort all namespaces

### ISSUE THREAD

**Issue by kyouma0220** [Leopotam/vscode-csharpfixformat#93]
### C# FixFormat extension version:
v0.0.78

### VsCode version:
January 2019 (version 1.31)

## Steps to reproduce
Look at marketplace Extension Settings.

The description of `sort.usings.order` does not describe how to sort all namespaces.

## Proposal
Add document about ```"csharpfixformat.sort.usings.order": "",```

## Expected  behavior
```json
"csharpfixformat.sort.usings.enabled": true,
"csharpfixformat.sort.usings.order": "",
```
```cs
using A;
using B;
using C;
using System;
```

## Actual behavior
```json
"csharpfixformat.sort.usings.enabled": true,
```
```cs
using System;
using A;
using B;
using C;
```

**Comment by Leopotam** [comment]
> Expected behavior
> "csharpfixformat.sort.usings.order": ""

Current behaviour simulate default settings from `visual studio` - all namespaces sorted alphabetically, but `System.xxx` placed always on top. Its why default value of `"csharpfixformat.sort.usings.order"` settings is `System`.

> The description of `sort.usings.order` does not describe how to sort all namespaces.

Usings always sorted alphabetically if `"csharpfixformat.sort.usings.enabled":true` and `"csharpfixformat.sort.usings.order"` setting just initializes `ignore list` of namespaces that should be placed first.

**Comment by Leopotam** [comment]
@kyouma0220 is it clear now?

**Comment by Leopotam** [comment]
No feedback, closed.
