### ISSUE TITLE
Format like VS Studio?

### ISSUE THREAD

**Issue by simkessy** [Leopotam/vscode-csharpfixformat#94]
How do I get it to format like VS Studio 2017 because right now it's changing between where I'm editing and I go back and forth a lot.

**Comment by Leopotam** [comment]
You mean, cursor position changed after code format? Then no how, because this code formatter works as whole-file formatter and if code lines amount will be changed - cursor position will be changed too. If you are talking about source code identity with vs after formatting - there are alot of settings, you can try to tune them for your code style as you want.

**Comment by simkessy** [comment]
I mean things like adding a space between functions and parentheses or having brackets on a different line, etc. My git diffs are all messed up because the formatting between the two IDEs are different. Wondering if there was a set of known settings I can use or if I just have to keep tweaking things until it's close.

**Comment by Leopotam** [comment]
All what you want can be tweaked with extension settings, you can find their description at `README`. There are no "rulesets", only separate rules, so, you need to tweak multiple settings.

For example:
> space between functions and parentheses

`csharpfixformat.style.spaces.beforeParenthesis: false`

> having brackets on a different line

`csharpfixformat.style.braces.onSameLine: false`

Just check `README`. And dont forget to read this line:
> If you need full format support of last C# version - better to write issue about proper formatting at [Omnisharp extension repo](https://github.com/OmniSharp/omnisharp-vscode/issues).

**Comment by Leopotam** [comment]
@simkessy is issue fixed for you?

**Comment by simkessy** [comment]
Some of the settings helped but I still get spacing issues with objects where object properties won't be indented properly and I don't see a setting to fix that.

**Comment by Leopotam** [comment]
> issues with objects where object properties won't be indented properly

Example? Did you checked [known issues](
https://github.com/Leopotam/vscode-csharpfixformat#known-issues)? This extension is not real c# ast parser, if you need some syntax that not supported right now - better to go to official [omnisharp extension repo](
https://github.com/OmniSharp/omnisharp-vscode/issues) and open issue for support required behaviour from Microsoft developers.

**Comment by Leopotam** [comment]
@simkessy no answers, I will re-open this issue again on new information from you.
