### ISSUE TITLE
Verbatim strings with 2 double quotes formatting

### ISSUE THREAD

**Issue by TRM79-Temp** [Leopotam/vscode-csharpfixformat#95]
### C# FixFormat extension version:
0.0.78

### VsCode version:
1.31.1

## Steps to reproduce
View | Command Palette | Format Selection (or Format Document)

## Expected  behavior
C# verbatim strings that contain two double quotes:
            Assert.Equal(@"<a href=""Test/Page1"">1</a>" +
                @"<a href=""Test/Page2"">2</a>" +
                @"<a href=""Test/Page3"">3</a>",
                output.Content.GetContent());

## Actual behavior
            Assert.Equal (@"<a href="
                "Test/Page1"
                ">1</a>" +
                @"<a href="
                "Test/Page2"
                ">2</a>" +
                @"<a href="
                "Test/Page3"
                ">3</a>",
                output.Content.GetContent ());

**Comment by Leopotam** [comment]
@TRM79-Temp I can only suggest you to use [special wrapping for ignore formatting](
https://github.com/Leopotam/vscode-csharpfixformat#special-flags) as quick fix. Cant give you any ETA for real fix.

**Comment by Leopotam** [comment]
@TRM79-Temp can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@TRM79-Temp no feedback, closed as fixed. 0.0.79 version released on marketplace.
