### ISSUE TITLE
'Format Selection' formats overall document

### ISSUE THREAD

**Issue by TRM79-Temp** [Leopotam/vscode-csharpfixformat#96]
### C# FixFormat extension version:
0.0.78

### VsCode version:
1.31.1

## Steps to reproduce
View | Command Palette | Format Selection

## Expected  behavior
Formats selection

## Actual behavior
Formats overall document

**Comment by Leopotam** [comment]
@TRM79-Temp not planned. You can do reproduce this behaviour through:
* New file.
* Select "csharp source" type for file.
* Insert selected code from your file.
* Format it as whole document.
