### ISSUE TITLE
Destructors cause unwanted formatting

### ISSUE THREAD

**Issue by Siccity** [Leopotam/vscode-csharpfixformat#97]
### C# FixFormat extension version:
0.0.78

### VsCode version:
1.31.1

## Steps to reproduce
Add a destructor to your script https://www.geeksforgeeks.org/destructors-in-c-sharp/

## Expected  behavior
```csharp
// Constructor
MyScript() {

}

// Destructor
~MyScript() {

}

void SomeMethod() {

}
```

## Actual behavior
```csharp
// Constructor
MyScript() {

	}

	// Destructor
	~MyScript() {

	}

void SomeMethod() {

}```

**Comment by Leopotam** [comment]
@Siccity can you check last state of develop branch? is issue fixed for you?

**Comment by Leopotam** [comment]
@Siccity no feedback, closed as fixed. 0.0.80 version released on marketplace.
