### ISSUE TITLE
Is possible don't remove the "white space"

### ISSUE THREAD

**Issue by GuerreroCraft61** [Leopotam/vscode-csharpfixformat#99]
## Steps to reproduce
https://gyazo.com/cd8a136938906b188cb414cf7db30c82

## Expected behavior
Don't remove the white space

## Actual behavior
Remove the white space

**Comment by Leopotam** [comment]
@GuerreroCraft61 I dont see any problems with current behaviour due its standard behaviour for microsoft omnisharp formatter too.
You can just dont keep empty line between braces and indents will be kept. When you will write new C# expression and reformat code - correct indent will be added.
